# standalone.mk -- build the celldiag pieces that do NOT need ./configure
#
#   make -f standalone.mk          # diag_logstream_dump + every runnable selftest
#   make -f standalone.mk check    # ... and run the selftests
#   make -f standalone.mk clean
#
# WHY THIS FILE EXISTS
# --------------------
# The celldiag parity checks (test_celldiag_replay_ab.py,
# test_celldiag_logstream_parity.py, celldiag_parity_status.py) define whether
# this tree's C decode path agrees with diaggrok. The top-level autoconf
# `./configure` hard-fails without libwebsockets >= 3.1.0, so on a host lacking
# that system library those checks would have no way to build what they test.
#
# Makefile.in cannot serve this purpose: it is rendered by the top-level
# config.status and its first line is `include ../Makefile.inc`, which is itself
# generated by configure. This file takes no autoconf input at all.
#
# WHAT `baseline` BUILDS
# --------------------
# `baseline` builds kismet_cap_cell_diag -- the Python-decode baseline helper --
# with NO autoconf input, reaching into NO ../diagspec/. It builds on Linux and
# Darwin, with or without libwebsockets. The shared config lives in
# baseline_platform.mk (capture_cell_at's `baseline` includes the same file).
#
# Two facts make that possible:
#
#   1. Every lws include, `struct lws_*` member and call site in
#      capture_framework.{c,h} is under `#ifdef HAVE_LIBWEBSOCKETS`, so the
#      helper needs libwebsockets only when the config enables it.
#
#   2. Nothing in the helper is structurally Linux-only. With a config.h naming
#      the actual OS (rather than asserting `#define SYS_LINUX 1` everywhere,
#      which pulls in <linux/sched.h>), Darwin links against libSystem alone.
#
# The generated config.h must therefore state only what is true of the host.
#
# What it still needs from the system: a C compiler. libwebsockets is used when
# present (LWS=auto), and libcap only when a copied ../config.h enables
# HAVE_CAPABILITY. A no-lws build loses only the remote-capture websocket
# transport, which no parity test uses; the build output says which you got.

CC      ?= cc
CFLAGS  ?= -Wall -g -O2
# No CXX / CXXFLAGS / DIAGSPEC_INC here, deliberately. Everything this file
# builds, the `baseline` helper included, is C. An -I into ../diagspec/ is
# exactly the dependency the target exists to not have, and defining the
# variables invites a future recipe to pick them up and quietly turn the
# baseline into a native build.

# The parity harness driver. diag_logstream.c + diag_hdlc.c and libc, nothing else.
LOGSTREAM_DUMP_BIN = diag_logstream_dump

# Every selftest in this directory that needs no capture framework.
TESTS = \
	test_diag_hdlc \
	test_diag_config \
	test_diag_capture \
	test_diag_rawlog \
	test_diag_capmeta \
	test_diag_clockanchor \
	test_diag_rawpkt \
	test_diag_optset \
	test_diag_stats \
	test_diag_profile \
	test_diag_portdiag \
	test_diag_ifclass \
	test_diag_wwanport \
	test_diag_probeclose \
	test_diag_modemident \
	test_diag_portadmit \
	test_diag_identvouch \
	test_diag_logstream \
	test_diag_bridgeq

# ===========================================================================
# baseline -- the Python-decode baseline helper, with no autoconf input
# ===========================================================================
BASELINE_DIR = build-baseline
# Not `kismet_cap_cell_diag` -- that is the generated Makefile's output path,
# and writing there would clobber a configured tree's helper. The failure is
# quiet: both builds exit 0, both are legitimately role `baseline` so both pass
# check_binary_symbols.sh, and .native_mode reads `baseline` either way, so
# nothing on disk tells you which makefile produced the binary. The symptom
# instead shows up as unrelated test failures (e.g. in argument handling) that
# point nowhere near the build system.
#
# celltools/Makefile's `replay-gate` target follows the same rule for the
# NATIVE=1/baseline pair -- "the two builds cannot coexist in the tree ... each
# binary is therefore copied out to $(GATE_DIR)". $(BASELINE_DIR) is ours alone
# and already .gitignore'd, so the check artifact lives there and the
# deliverable path has exactly one writer.
BASELINE_BIN = $(BASELINE_DIR)/kismet_cap_cell_diag

# The SAME pure-C modules Makefile.in's MONITOR_OBJS names, and the count is
# pinned for the SAME reason: a shorter list still builds, still links, and
# still passes every selftest while silently dropping a capability. Two lists in
# two files can drift, so the parity-discovery test in celltools/tests diffs
# this set against Makefile.in's.
BASELINE_CELLDIAG_SRCS = \
	capture_cell_diag.c \
	diag_hdlc.c \
	diag_config.c \
	diag_capture.c \
	diag_rawlog.c \
	diag_capmeta.c \
	diag_clockanchor.c \
	diag_rawpkt.c \
	diag_profile.c \
	diag_portdiag.c \
	diag_ifclass.c \
	diag_wwanport.c \
	diag_logstream.c \
	diag_stats.c \
	diag_optset.c \
	diag_probeclose.c \
	diag_modemident.c \
	diag_portadmit.c \
	diag_identvouch.c \
	diag_bridgeq.c
BASELINE_SRCS_COUNT = 20

# The extern "C" surface with nothing behind it. capture_cell_diag.c references
# diag_native_decode() at LINK scope regardless of the runtime nativedecode=
# branch, so the baseline needs the stub, not a shorter link line.
BASELINE_STUB_SRC = diag_native_decode_stub.c

# The capture framework -- what libkismetdatasource.a is, unpacked -- compiled
# from source so the target needs no prior top-level build. Its headers are
# listed too, as PREREQUISITES: the parity gauge's staleness guard
# (celltools/celldiag_parity.py, link_dependencies) derives a build-baseline/
# binary's closure from THIS rule, and a closure without the framework reads
# "current" after a framework edit. Mirrored in the sibling capture directory's
# standalone.mk; both sit one level below the tree root, so the paths agree.
BASELINE_KISMET_SRCS = \
	../capture_framework.c \
	../simple_ringbuf_c.c \
	../mpack/mpack.c
BASELINE_KISMET_HDRS = \
	../capture_framework.h \
	../simple_ringbuf_c.h \
	../mpack/mpack.h \
	../kis_external_packet.h \
	../kis_endian.h \
	../remote_announcement.h \
	../version.h


# -I$(BASELINE_DIR) FIRST so our generated config.h/version.c win; -I.. resolves
# ../capture_framework.h, ../mpack/mpack.h and friends.
#
# CELLDIAG_NATIVE_MODE is stated rather than left to capture_cell_diag.c's
# fallback: this target IS the baseline by construction (it has no NATIVE=1
# counterpart), so the value is known here and saying it keeps the two build
# systems agreeing out loud instead of by coincidence.
BASELINE_CFLAGS = -I$(BASELINE_DIR) -I.. -DCELLDIAG_NATIVE_MODE=\"baseline\" \
	$(BASELINE_LWS_CFLAGS) $(CFLAGS)

baseline: $(BASELINE_BIN)

# AFTER `baseline:` so `baseline` stays this file's default goal -- the fragment
# defines rules of its own, and the first rule make reads is the default.
include baseline_platform.mk

# The platform guard, config.h and version.c rules live in baseline_platform.mk.
# The guard refuses only an OS with no SYS_* mapping.
#
# NOTE: `check` is NOT the same claim as `baseline`. It builds no capture framework
# at all, so a green `check` says nothing about whether the helper links.

# baseline-platform-guard FIRST, so an unmapped OS gets an explanation instead
# of pages of clang output. It is listed on $(BASELINE_BIN) rather
# than on `baseline` because $(BASELINE_BIN) is the target that actually invokes
# the compiler -- a guard on the phony alias alone would be bypassed by anyone
# naming the binary path directly.
$(BASELINE_BIN): baseline-platform-guard \
		$(BASELINE_DIR)/config.h $(BASELINE_DIR)/version.c \
		$(BASELINE_CELLDIAG_SRCS) $(BASELINE_STUB_SRC) \
		$(BASELINE_KISMET_SRCS) $(BASELINE_KISMET_HDRS)
	@[ "$(words $(BASELINE_CELLDIAG_SRCS))" = "$(BASELINE_SRCS_COUNT)" ] || { \
	    echo "*** ERROR: BASELINE_CELLDIAG_SRCS has $(words $(BASELINE_CELLDIAG_SRCS)) sources, expected $(BASELINE_SRCS_COUNT) ***" >&2; \
	    echo "A pure-C module was added or LOST.  A shorter list still links and" >&2; \
	    echo "still passes check -- diag_logstream is what the logstream parity" >&2; \
	    echo "check runs on." >&2; \
	    exit 1; }
	$(CC) $(BASELINE_CFLAGS) -o $@ \
	    $(BASELINE_CELLDIAG_SRCS) $(BASELINE_STUB_SRC) \
	    $(BASELINE_KISMET_SRCS) $(BASELINE_DIR)/version.c \
	    -lpthread -lm $(BASELINE_CONFIG_LIBS)
	@echo "PASS: baseline $(BASELINE_BIN) built with no autoconf input"
	@echo "      (a CHECK artifact -- the tree's ./kismet_cap_cell_diag is untouched)"
# The same post-link polarity assertion the autoconf baseline link runs, when a
# ../diagspec/ directory is present to supply it. Absent, this target is still a
# legitimate build -- the whole point is that it works on a tree that has no
# ../diagspec/ at all -- so its absence SKIPS rather than fails, and says so.
	@if [ -f ../diagspec/check_binary_symbols.sh ]; then \
	    sh ../diagspec/check_binary_symbols.sh baseline $(BASELINE_BIN) ..; \
	else \
	    echo "  (symbol guard skipped: no ../diagspec/ in this tree)"; \
	fi

all: $(LOGSTREAM_DUMP_BIN) $(TESTS)

$(LOGSTREAM_DUMP_BIN): diag_logstream.c diag_logstream.h diag_hdlc.c diag_hdlc.h
	$(CC) $(CFLAGS) -DDIAG_LOGSTREAM_DUMP -o $@ diag_logstream.c diag_hdlc.c

test_diag_hdlc: diag_hdlc.c diag_hdlc.h
	$(CC) $(CFLAGS) -DDIAG_HDLC_SELFTEST -o $@ diag_hdlc.c

test_diag_config: diag_config.c diag_config.h diag_hdlc.c diag_capture.c
	$(CC) $(CFLAGS) -DDIAG_CONFIG_SELFTEST -o $@ diag_config.c diag_hdlc.c diag_capture.c

test_diag_capture: diag_capture.c diag_capture.h diag_hdlc.c diag_hdlc.h
	$(CC) $(CFLAGS) -DDIAG_CAPTURE_SELFTEST -o $@ diag_capture.c diag_hdlc.c

test_diag_rawlog: test_diag_rawlog.c diag_rawlog.c diag_rawlog.h
	$(CC) $(CFLAGS) -o $@ test_diag_rawlog.c diag_rawlog.c

test_diag_capmeta: test_diag_capmeta.c diag_capmeta.c diag_capmeta.h
	$(CC) $(CFLAGS) -o $@ test_diag_capmeta.c diag_capmeta.c

test_diag_clockanchor: test_diag_clockanchor.c diag_clockanchor.c diag_clockanchor.h \
		diag_hdlc.c diag_hdlc.h diag_capmeta.c diag_capmeta.h
	$(CC) $(CFLAGS) -o $@ test_diag_clockanchor.c diag_clockanchor.c diag_hdlc.c diag_capmeta.c

test_diag_rawpkt: test_diag_rawpkt.c diag_rawpkt.c diag_rawpkt.h
	$(CC) $(CFLAGS) -o $@ test_diag_rawpkt.c diag_rawpkt.c

test_diag_optset: test_diag_optset.c diag_optset.c diag_optset.h
	$(CC) $(CFLAGS) -o $@ test_diag_optset.c diag_optset.c

test_diag_stats: test_diag_stats.c diag_stats.c diag_stats.h
	$(CC) $(CFLAGS) -o $@ test_diag_stats.c diag_stats.c

test_diag_profile: test_diag_profile.c diag_profile.c diag_profile.h
	$(CC) $(CFLAGS) -o $@ test_diag_profile.c diag_profile.c

test_diag_portdiag: test_diag_portdiag.c diag_portdiag.c diag_portdiag.h
	$(CC) $(CFLAGS) -o $@ test_diag_portdiag.c diag_portdiag.c

test_diag_ifclass: test_diag_ifclass.c diag_ifclass.c diag_ifclass.h
	$(CC) $(CFLAGS) -o $@ test_diag_ifclass.c diag_ifclass.c

test_diag_wwanport: diag_wwanport.c diag_wwanport.h
	$(CC) $(CFLAGS) -DDIAG_WWANPORT_SELFTEST -o $@ diag_wwanport.c

test_diag_probeclose: diag_probeclose.c diag_probeclose.h
	$(CC) $(CFLAGS) -pthread -DDIAG_PROBECLOSE_SELFTEST -o $@ diag_probeclose.c

# The ModemIdentity record: AT value extraction, label, JSON. libc only.
test_diag_modemident: test_diag_modemident.c diag_modemident.c diag_modemident.h
	$(CC) $(CFLAGS) -o $@ test_diag_modemident.c diag_modemident.c

# Which USB serial ttys a scan may open at all: a fake sysfs tree, no device.
test_diag_portadmit: diag_portadmit.c diag_portadmit.h
	$(CC) $(CFLAGS) -DDIAG_PORTADMIT_SELFTEST -o $@ diag_portadmit.c

# The holder's identity vouch: publish/lookup/withdraw and its rules. libc only.
test_diag_identvouch: test_diag_identvouch.c diag_identvouch.c diag_identvouch.h diag_modemident.c diag_modemident.h
	$(CC) $(CFLAGS) -o $@ test_diag_identvouch.c diag_identvouch.c diag_modemident.c

# The decoder input queue. libc only.
test_diag_bridgeq: test_diag_bridgeq.c diag_bridgeq.c diag_bridgeq.h
	$(CC) $(CFLAGS) -o $@ test_diag_bridgeq.c diag_bridgeq.c

test_diag_logstream: diag_logstream.c diag_logstream.h diag_hdlc.c diag_hdlc.h
	$(CC) $(CFLAGS) -DDIAG_LOGSTREAM_SELFTEST -o $@ diag_logstream.c diag_hdlc.c

check: $(TESTS)
	@for t in $(TESTS); do echo "--- $$t"; ./$$t || exit 1; done
	@echo "PASS: standalone celldiag selftests"

# $(BASELINE_BIN) lives INSIDE $(BASELINE_DIR), so the `rm -rf` below covers it
# and never touches the generated Makefile's ./kismet_cap_cell_diag.
#
# $(BASELINE_DIR) is ours alone -- nothing else in the tree names it except
# .gitignore -- and leaving a stale build-baseline/ behind is how a "clean
# rebuild" reads green off yesterday's config.h.
clean:
	rm -f $(LOGSTREAM_DUMP_BIN) $(TESTS)
	rm -rf $(BASELINE_DIR)
	rm -rf $(FUNCTIONAL_DIR)
	rm -rf $(CONTRACT_DIR)

# `baseline` is PHONY-listed even though it has a real prerequisite: a file named
# `baseline` in this directory would otherwise shadow the target and make it a
# silent no-op -- the same class of green-but-inert failure the baseline guard
# exists to prevent.
.PHONY: all baseline check clean functional contract

# ── deps: the public decoder, at a PINNED ref ────────────────────────────────
# The bridge (kismet_diag_decode.py) holds no parsers; diaggrok is the decoder.
# It is a DEPENDENCY, not a vendored copy: vendoring would make these decoders a
# fork of the upstream ones, so every later parser fix would silently stop
# reaching this tree.
#
# The ref is PINNED and the pin is the decode contract. A floating branch
# would mean this tree decodes differently on two different days with no commit
# in between.
#
# No venv, no pip, no wheels: diaggrok declares `dependencies = []`, so its
# src/ on PYTHONPATH under the system python3 is the whole install.
# The ref is a RELEASE TAG, and the SHA beside it is what makes the tag safe to
# name. A tag is a pointer the publisher can move; a SHA cannot be moved. Naming
# only the tag would reintroduce, slowly, the same "decodes differently on two
# different days" failure a branch gives you quickly. So `deps` fetches the tag
# -- which is the human-legible release name -- and then ASSERTS
# that it still resolves to the commit this tree was tested against. If upstream
# ever re-points the tag, this fails loudly at fetch time instead of silently
# changing what the bridge decodes.
DIAGGROK_URL ?= https://github.com/lukejenkins/diaggrok
DIAGGROK_REF ?= v2026.10.04
DIAGGROK_SHA ?= 005d14f8fddba3ed5f53ac87e67fabf19490d3d3
DIAGGROK_DIR ?= .deps/diaggrok

.PHONY: deps
# A SYMLINKED $(DIAGGROK_DIR) is a development decoder: the binary
# decodes with whatever .deps/diaggrok is, so a developer points it at a working
# tree. `deps` never fetches into one -- `git -C` through the link would operate
# on the linked tree's repository -- and says so instead of cloning over it. To
# run `functional`/`contract` against the PINNED decoder beside such a link, pass
# DIAGGROK_DIR=<another directory>.
deps:
	@if [ -L "$(DIAGGROK_DIR)" ]; then \
	    echo "deps: FAILED -- $(DIAGGROK_DIR) is a symlink (to $$(readlink "$(DIAGGROK_DIR)"))," >&2; \
	    echo "      a development decoder, not the pinned fetch. Nothing was fetched." >&2; \
	    echo "      For the PINNED decoder, pass DIAGGROK_DIR=<another directory>." >&2; \
	    exit 1; \
	fi
	@if [ ! -d "$(DIAGGROK_DIR)/.git" ]; then \
	    mkdir -p "$$(dirname $(DIAGGROK_DIR))"; \
	    git clone --quiet "$(DIAGGROK_URL)" "$(DIAGGROK_DIR)"; \
	fi
	@git -C "$(DIAGGROK_DIR)" fetch --quiet --force --tags origin "$(DIAGGROK_REF)" 2>/dev/null || \
	    git -C "$(DIAGGROK_DIR)" fetch --quiet --force --tags origin
	@git -C "$(DIAGGROK_DIR)" checkout --quiet --detach "$(DIAGGROK_REF)"
	@head=$$(git -C "$(DIAGGROK_DIR)" rev-parse HEAD); \
	if [ "$$head" != "$(DIAGGROK_SHA)" ]; then \
	    echo "deps: FAILED -- $(DIAGGROK_REF) resolves to $$head," >&2; \
	    echo "      but this tree is pinned to $(DIAGGROK_SHA)." >&2; \
	    echo "      The upstream tag moved. Do not paper over this by editing" >&2; \
	    echo "      DIAGGROK_SHA: re-run the parity checks first." >&2; \
	    exit 1; \
	fi; \
	echo "deps: diaggrok pinned at $(DIAGGROK_REF) ($$head)"

# ===========================================================================
# install-decoder -- the installed layout's bridge + decoder
# ===========================================================================
# Called by the top-level `make install` with CELL_SHARE=$(SHARE)cell. Installs:
#   $(CELL_SHARE)/kismet_diag_decode.py              the bridge (always)
#   $(CELL_SHARE)/.deps/diaggrok/src/diaggrok/...    the decoder, if fetched
# The relative layout is a tree's own, so the binary's data-dir candidate uses
# the same resolver code as the tree walk.
#
# No network. This never fetches: `deps` is the one step that touches the
# network, and it stays explicit. It installs what `deps` put in
# $(DIAGGROK_DIR), and ONLY IF its HEAD is the pinned $(DIAGGROK_SHA) -- the
# pin is what the parity checks were run against, so an unpinned decoder is not
# installed at all (a warning, not a failure: the rest of Kismet still
# installs, and the installed celldiag then refuses at open, naming the fix).
CELL_SHARE ?=
INSTALL_DATA ?= install -m 644
.PHONY: install-decoder
install-decoder:
	@[ -n "$(CELL_SHARE)" ] || { echo "install-decoder: CELL_SHARE is unset" >&2; exit 1; }
	@mkdir -p "$(CELL_SHARE)"
	@$(INSTALL_DATA) kismet_diag_decode.py "$(CELL_SHARE)/kismet_diag_decode.py"
	@head=$$(git -C "$(DIAGGROK_DIR)" rev-parse HEAD 2>/dev/null); \
	if [ ! -d "$(DIAGGROK_DIR)/src/diaggrok" ]; then \
	    echo "*** celldiag: NO DECODER INSTALLED -- $(DIAGGROK_DIR) was never fetched." >&2; \
	    echo "*** Run \`make -f standalone.mk deps\` in capture_cell_diag/, then \`make install\` again." >&2; \
	elif [ ! -e "$(DIAGGROK_DIR)/.git" ] || [ "$$head" != "$(DIAGGROK_SHA)" ]; then \
	    echo "*** celldiag: NO DECODER INSTALLED -- $(DIAGGROK_DIR) is at '$$head'," >&2; \
	    echo "*** not the pinned $(DIAGGROK_REF) ($(DIAGGROK_SHA))." >&2; \
	    echo "*** Run \`make -f standalone.mk deps\` in capture_cell_diag/, then \`make install\` again." >&2; \
	else \
	    rm -rf "$(CELL_SHARE)/.deps/diaggrok"; \
	    mkdir -p "$(CELL_SHARE)/.deps/diaggrok/src"; \
	    cp -RL "$(DIAGGROK_DIR)/src/diaggrok" "$(CELL_SHARE)/.deps/diaggrok/src/"; \
	    find "$(CELL_SHARE)/.deps/diaggrok" -name __pycache__ -type d -prune -exec rm -rf {} +; \
	    echo "$$head" > "$(CELL_SHARE)/.deps/diaggrok/PINNED_SHA"; \
	    chmod -R a+rX "$(CELL_SHARE)/.deps"; \
	    echo "celldiag: installed decoder $(DIAGGROK_REF) ($$head) in $(CELL_SHARE)"; \
	fi

# ===========================================================================
# functional -- the tree's own self-test, on canned input it owns
# ===========================================================================
# `baseline` proves the helper BUILDS without autoconf, which says nothing
# about whether it decodes. This target makes the stronger claim: this tree, on
# any machine, decodes a capture it ships itself into cell observations.
#
# The fixture is in-tree on purpose. A test that relies on captures outside the
# source tree skips on every machine that lacks them, and a skip is not a pass.
#
# No autoconf, no libwebsockets, no Kismet server, no venv. Unlike `baseline`
# this target compiles nothing: it runs the decode bridge directly on the
# fixture. The bridge's `--replay` is the same deframe path the C helper's
# `replay=` source option drives, so this exercises the decode half end to end
# while needing only a python3 and the pinned decoder.
#
# System python3 and an explicit PYTHONPATH are both required. A developer venv
# may carry diaggrok as an editable install, which arrives via a .pth in
# site-packages, and Python loads a .pth regardless of PYTHONPATH. Under such an
# interpreter this target would decode with the developer's working tree while
# appearing to use the pinned dependency, and nothing on the terminal would
# distinguish the two. Scrubbing the environment cannot unhook a .pth, so the
# fix is the interpreter, not the environment.
#
# This is also the helper's own deployment model: capture_cell_diag.c's
# resolve_python runs python3 off $PATH with the fetched decoder first on
# PYTHONPATH (`PYTHONPATH=.deps/…`), so a venv-less tree this target passes on
# is one the C `helper_dir_check()` accepts.
#
#   If you override PYTHON=, override it with a bare interpreter. Pointing it
#   at a venv that has diaggrok installed makes this test meaningless.

PYTHON        ?= python3
FUNCTIONAL_DIR      = build-functional
FUNCTIONAL_FIXTURE  = fixtures/functional.hdlc
FUNCTIONAL_EXPECTED = fixtures/functional.expected.json
FUNCTIONAL_OBSERVED = $(FUNCTIONAL_DIR)/observed.jsonl
# All-zero synthetic IMEI. The bridge requires --imei and stamps it into
# prov.imei; a real one would be PII in a file that ships publicly.
FUNCTIONAL_IMEI     = 000000000000000

functional: deps
	@mkdir -p $(FUNCTIONAL_DIR)
	@[ -f $(FUNCTIONAL_FIXTURE) ] || { \
	    echo "*** ERROR: missing $(FUNCTIONAL_FIXTURE) ***" >&2; \
	    echo "Regenerate it with:" >&2; \
	    echo "    $(PYTHON) fixtures/make_functional_fixture.py --out $(FUNCTIONAL_FIXTURE)" >&2; \
	    exit 1; }
	@echo "--- replaying $(FUNCTIONAL_FIXTURE) through the decode bridge"
# `--no-inventory` so stdout is pure cell_observation lines: the periodic
# diag_inventory census is a health readout, not an observation, and the C
# helper never relays it through cf_send_json either.
#
# Separate statements, NOT a pipeline. The bridge exits 1 when it refuses a
# file that is not a DIAG capture, and piping its stdout anywhere would make the
# recipe read the last command's status instead of the decoder's, reporting a
# false pass. Redirect to a file, then check.
	env PYTHONPATH=$(DIAGGROK_DIR)/src \
	    $(PYTHON) kismet_diag_decode.py \
	        --imei $(FUNCTIONAL_IMEI) --no-inventory \
	        --replay $(FUNCTIONAL_FIXTURE) > $(FUNCTIONAL_OBSERVED)
	@$(PYTHON) fixtures/check_functional.py \
	    $(FUNCTIONAL_OBSERVED) $(FUNCTIONAL_EXPECTED)
	@echo "PASS: functional -- the tree decoded its own capture with no external input"

# ===========================================================================
# contract -- the PINNED diaggrok satisfies the bridge's runtime contract
# ===========================================================================
# `functional` runs with `--no-inventory`, which sets `inventory=None` in the
# bridge and so skips the census `finish()` path entirely. That path is the one
# place the bridge reads fields straight out of the pinned diaggrok's
# `DiagInventory.summary()` (silent_actionable_total and its sibling counts), so
# it is where a bridge that has outrun the pinned decoder crashes: a pin that
# lacks a field the bridge reads decodes every record and then dies at finish()
# with exit 70 (KeyError), while `functional` stays green.
#
# It is a separate target because `functional`'s `--no-inventory` is needed for
# its own claim: pure cell_observation lines to byte-diff against
# functional.expected.json. This target runs the SAME fixture through the SAME
# pinned decoder with the census ON and asserts the census rendered.
#
# `--inventory-interval 0` disables the PERIODIC census but NOT the final
# `finish()` snapshot (see _emit_records.finish: it fires whenever inventory is
# not None). So the only census line emitted is the deterministic finish() one
# -- which is exactly the contract-reading line -- and there is no timing race.
#
# The SHA guard in `deps` does not cover this. That guard catches a tag the
# publisher moved; a tag whose library lags the bridge consuming it resolves to
# the right SHA and still crashes. This target is the only check that runs the
# bridge and the pinned library together. If it fails, re-pin
# `DIAGGROK_REF`/`DIAGGROK_SHA` to a diaggrok release that has the field; do not
# reintroduce `--no-inventory` here, which would hide the failure.
#
# Same system-python3 + explicit PYTHONPATH discipline as `functional`, for the
# same reasons (see that target's header): a venv with diaggrok on a .pth would
# decode via the developer's working tree instead of the pin.
CONTRACT_DIR      = build-contract
CONTRACT_OBSERVED = $(CONTRACT_DIR)/observed.jsonl

contract: deps
	@mkdir -p $(CONTRACT_DIR)
	@[ -f $(FUNCTIONAL_FIXTURE) ] || { \
	    echo "*** ERROR: missing $(FUNCTIONAL_FIXTURE) ***" >&2; \
	    echo "Regenerate it with:" >&2; \
	    echo "    $(PYTHON) fixtures/make_functional_fixture.py --out $(FUNCTIONAL_FIXTURE)" >&2; \
	    exit 1; }
	@echo "--- contract: replaying $(FUNCTIONAL_FIXTURE) through the bridge WITH the census"
# Separate statements, NOT a pipeline: a crashing bridge exits 70, and piping
# its stdout would make the recipe read the last command's status instead.
# Redirect to a file, then check. The bridge's own non-zero exit is the FIRST
# half of this check; check_contract.py is the second (non-vacuous census).
	env PYTHONPATH=$(DIAGGROK_DIR)/src \
	    $(PYTHON) kismet_diag_decode.py \
	        --imei $(FUNCTIONAL_IMEI) --inventory-interval 0 \
	        --replay $(FUNCTIONAL_FIXTURE) > $(CONTRACT_OBSERVED)
	@$(PYTHON) fixtures/check_contract.py $(CONTRACT_OBSERVED)
	@echo "PASS: contract -- the pinned diaggrok satisfies the bridge finish() census contract"
