# SPDX-License-Identifier: Apache-2.0
"""Discovery + skip-reason contract for the parity harnesses.

A skipped harness and a passing one must not produce the same silence:
something has to say whether the decode contract was checked. These tests pin
the two properties that guarantee that:

1. **Discovery works with no environment at all** -- the common case (you built
   the tree, then ran the tests) needs nothing exported, so "nobody set the env
   var" stops being a reason the contract goes unchecked.
2. **The skip reasons are distinguishable** -- "this is not a source tree"
   (a fact about where you are pointed) never renders as the same string as
   "the sources are here and nobody built the driver" (a fact about nobody
   having run it).

Property 2 is tested by pointing discovery at synthetic directories under
``tmp_path``, so it holds whatever state the real tree is in -- which is also
rule 1 of the boundary this directory enforces, applied to itself.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

import celldiag_parity as parity


def test_every_role_names_its_env_var_and_make_target():
    """The make targets live in ``ROLES``, not only in a harness docstring, so
    a command like `make -C capture_cell_diag logstream-dump` is discoverable
    where a reader of the harness would look."""
    assert set(parity.ROLES) == {"celldiag", "logstream", "cellat"}
    for role, (env_var, rel, target) in parity.ROLES.items():
        assert env_var.startswith("KP_") and env_var.endswith("_BIN")
        # Roles do not all live in one subdirectory (cellat is in a different
        # one), so do not assert a fixed prefix. The property actually needed
        # is that the make target is the binary's basename, so
        # `_subdir_for(rel)` + target is a build command for any subdirectory.
        subdir, _, base = rel.partition("/")
        assert subdir.startswith("capture_cell_") and base
        assert target


def test_absent_tree_and_unbuilt_driver_are_DIFFERENT_statuses(tmp_path, monkeypatch):
    """Both are skips; they must never be the same skip.

    Being pointed at something that is not a source tree is benign -- the gauge
    reports it and moves on. An unbuilt driver in a tree that IS here is the
    finding, because it means the contract could have been checked and was
    not."""
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    monkeypatch.delenv("CELLDIAG_PARITY_BUILD", raising=False)

    # (a) not a source tree at all
    monkeypatch.setattr(parity, "_TREE_ROOT", tmp_path / "empty")
    absent = parity.discover("celldiag")
    assert absent.status == "no-tree" and not absent.ok

    # (b) a tree that exists, IS configured, and was never built.
    #     The generated Makefiles are load-bearing in this fixture: without
    #     them the tree is *unconfigured*, a third, distinct status, and the
    #     fixture would model "unconfigured" while asserting "unbuilt".
    clone = tmp_path / "tree"
    (clone / "capture_cell_diag").mkdir(parents=True)
    (clone / "Makefile").write_text("# generated by ./configure\n")
    (clone / "capture_cell_diag" / "Makefile").write_text("# generated\n")
    monkeypatch.setattr(parity, "_TREE_ROOT", clone)
    unbuilt = parity.discover("celldiag")
    assert unbuilt.status == "not-built" and not unbuilt.ok

    assert absent.status != unbuilt.status
    assert absent.skip_reason() != unbuilt.skip_reason()
    # The actionable one carries the command that fixes it.
    assert "make -C" in unbuilt.skip_reason()
    assert "make -C" not in absent.skip_reason()


def test_a_present_built_driver_is_found_with_no_env(tmp_path, monkeypatch):
    """Property 1, tested against a fabricated tree so it holds everywhere."""
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    clone = tmp_path / "tree"
    rel = parity.ROLES["logstream"][1]
    exe = clone / rel
    exe.parent.mkdir(parents=True, exist_ok=True)
    exe.write_text("#!/bin/sh\nexit 0\n")
    exe.chmod(0o755)
    monkeypatch.setattr(parity, "_TREE_ROOT", clone)

    found = parity.discover("logstream")
    assert found.status == "discovered" and found.path == exe


def test_an_explicit_env_var_still_wins(tmp_path, monkeypatch):
    """Discovery is a fallback, not an override: an operator pointing at a
    binary outside this tree must keep getting that binary."""
    exe = tmp_path / "elsewhere"
    exe.write_text("#!/bin/sh\nexit 0\n")
    exe.chmod(0o755)
    monkeypatch.setenv("KP_CELLDIAG_BIN", str(exe))
    found = parity.discover("celldiag")
    assert found.status == "env" and found.path == exe


def test_a_bad_env_var_is_reported_not_silently_replaced(tmp_path, monkeypatch):
    """If the operator set the variable and it is wrong, say so -- falling
    through to discovery would run a DIFFERENT binary than the one asked for and
    report agreement about it."""
    monkeypatch.setenv("KP_CELLDIAG_BIN", str(tmp_path / "nope"))
    found = parity.discover("celldiag")
    assert found.status == "env-bad" and not found.ok


def test_unknown_role_is_an_error_not_a_skip():
    with pytest.raises(ValueError):
        parity.discover("no-such-role")


# ---------------------------------------------------------------------------
# An unconfigured tree is its own status, and a run that executed nothing is
# not a PASS.
# ---------------------------------------------------------------------------


def _unconfigured_clone(tmp_path, monkeypatch=None):
    """A tree as it comes off `git clone`: Makefile.in, no Makefile."""
    clone = tmp_path / "tree"
    (clone / "capture_cell_diag").mkdir(parents=True)
    (clone / "Makefile.in").write_text("# autotools template\n")
    (clone / "capture_cell_diag" / "Makefile.in").write_text("# template\n")
    if monkeypatch is not None:
        monkeypatch.setattr(parity, "_TREE_ROOT", clone)
    return clone


def test_an_unconfigured_clone_is_not_reported_as_build_failed(tmp_path, monkeypatch):
    """`build-failed` means "a real breakage -- investigate".

    An unconfigured tree is not a breakage, it is a fact about the host, and
    make's *"No rule to make target"* says nothing about the target name. The
    status must name the actual condition and carry the actual remedy.
    """
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    _unconfigured_clone(tmp_path, monkeypatch)
    # Pin the configure-dep probe: on a host MISSING a configure-time dep the
    # correct status is `not-configurable`, so without this the test's answer
    # depends on which machine runs it.
    monkeypatch.setattr(parity, "missing_configure_deps", lambda clone: [])

    found = parity.discover("celldiag", allow_build=True)
    assert found.status == "not-configured", \
        f"unconfigured tree reported as {found.status!r}"
    assert not found.ok
    assert "./configure" in found.skip_reason()


def test_an_unconfigured_clone_stays_not_configured_even_under_build(tmp_path, monkeypatch):
    """Opting into --build must not turn this into `build-failed`.

    The check precedes the build branch precisely so that `make` is never
    invoked in a tree where it cannot work; otherwise the accurate status is
    destroyed by the very attempt that was doomed by it.
    """
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    _unconfigured_clone(tmp_path, monkeypatch)
    monkeypatch.setenv("CELLDIAG_PARITY_BUILD", "1")
    monkeypatch.setattr(parity, "missing_configure_deps", lambda clone: [])

    called = []
    monkeypatch.setattr(parity, "_build",
                        lambda *a, **k: called.append(a) or (False, "boom"))

    found = parity.discover("celldiag")
    assert found.status == "not-configured"
    assert called == [], "make was invoked on a tree with no makefile"


def test_not_configured_is_actionable_not_benign():
    """It is fixable HERE, so --check must still flag it.

    `no-tree` is excusable (the operator is not pointed at a source tree at
    all); `not-configured` is one command away. Lumping them would re-hide the
    case.
    """
    import celldiag_parity_status as gauge
    assert "no-tree" in gauge._BENIGN
    assert "not-configured" not in gauge._BENIGN


def test_three_skip_reasons_are_mutually_distinguishable(tmp_path, monkeypatch):
    """no-tree / not-configured / not-built must be three different strings."""
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    monkeypatch.delenv("CELLDIAG_PARITY_BUILD", raising=False)

    monkeypatch.setattr(parity, "_TREE_ROOT", tmp_path / "empty")
    absent = parity.discover("celldiag")

    clone = _unconfigured_clone(tmp_path, monkeypatch)
    monkeypatch.setattr(parity, "missing_configure_deps", lambda clone: [])
    unconfigured = parity.discover("celldiag")

    (clone / "Makefile").write_text("# generated\n")
    (clone / "capture_cell_diag" / "Makefile").write_text("# generated\n")
    unbuilt = parity.discover("celldiag")

    statuses = {absent.status, unconfigured.status, unbuilt.status}
    assert statuses == {"no-tree", "not-configured", "not-built"}
    reasons = {absent.skip_reason(), unconfigured.skip_reason(), unbuilt.skip_reason()}
    assert len(reasons) == 3

    # Each actionable one carries ITS OWN remedy, not the other's.
    assert "./configure" in unconfigured.skip_reason()
    assert "./configure" not in unbuilt.skip_reason()
    assert "make -C" in unbuilt.skip_reason()


def test_the_gauge_names_a_harness_for_every_role():
    """A role with no harness is a driver nothing ever runs.

    ``report()`` indexes ``HARNESS[d.role]``, so a forgotten role is a KeyError
    at gauge time rather than silence, which is a poor place to learn it; the
    reverse direction (a HARNESS entry pointing at a file that does not exist)
    raises nothing at all. Both are asserted here.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    assert set(gauge.HARNESS) == set(parity.ROLES), (
        "every discovery role needs a harness the gauge can name")
    for role, rel in gauge.HARNESS.items():
        assert (Path(gauge.CELLTOOLS) / rel).is_file(), \
            f"role {role} names a harness that does not exist: {rel}"


def _verdict(discoveries, rc=0, **counts):
    """Drive the verdict from (discovery, rc, what pytest ACTUALLY ran).

    Discovery state alone cannot tell "ran" from "skipped"; the counts can.
    Default per-harness counts mean "ran cleanly", so a test states only the
    harness it cares about.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    resolved = {role: gauge.Counts(**counts.get(role, {"passed": 3}))
                for role in gauge.HARNESS}
    return gauge.verdict(discoveries, rc, resolved)


def _d(role, ok):
    return parity.Discovery(role, "discovered" if ok else "not-configured",
                            Path("/x") if ok else None, "")


_NOTHING = {"passed": 0, "skipped": 12, "reason": "no replay capture"}


def test_a_run_where_no_driver_existed_is_NOT_a_pass():
    """The gauge's own failure mode, form 1: no driver anywhere.

    On an unconfigured tree both harnesses skip and pytest exits 0. That must
    not render as PASS: "nothing complained" is not "the contract was checked".
    """
    line, ret = _verdict([_d("celldiag", False), _d("logstream", False)],
                         celldiag=_NOTHING, logstream=_NOTHING)
    assert "NO-OP" in line and "PASS" not in line
    assert "no harness had a driver" in line
    assert ret == 1, "an all-skipped run must not hand back success"


def test_drivers_present_but_every_test_skipped_is_NOT_a_pass():
    """The gauge's own failure mode, form 2: drivers built, nothing ran.

    Discovery answers "is there a driver?", but both harnesses also skip when
    the replay capture is absent (captures live outside git), which is the
    likelier miss. The verdict therefore keys on what pytest actually ran,
    which `--junitxml` reports per test, not on discovery state alone.
    """
    line, ret = _verdict([_d("celldiag", True), _d("logstream", True)],
                         celldiag=_NOTHING, logstream=_NOTHING)
    assert "NO-OP" in line and "PASS" not in line
    assert ret == 1
    # It must not blame an absent driver -- every driver was present. Naming the
    # wrong cause sends the operator to `--build`, which cannot help.
    assert "no harness had a driver" not in line
    assert "SKIPPED every test" in line and "no replay capture" in line, (
        "the verdict must carry pytest's own skip reason, or the operator "
        "cannot tell which silence this is")


def test_a_partial_run_says_which_half_is_unverified():
    line, ret = _verdict([_d("celldiag", True), _d("logstream", False)],
                         logstream=_NOTHING)
    assert "PARTIAL" in line and "logstream" in line
    assert ret == 0


def test_a_harness_that_half_skipped_is_PARTIAL_not_PASS():
    """Discovery says ran; the counts say half of it did not.

    A verdict keyed on discovery alone never sees a skip it did not predict.
    """
    line, ret = _verdict([_d("celldiag", True), _d("logstream", True)],
                         logstream={"passed": 2, "skipped": 2,
                                    "reason": "no NR fixture"})
    assert "PARTIAL" in line and "PASS" not in line
    assert "logstream" in line and "no NR fixture" in line
    assert ret == 0


def test_a_genuine_full_run_still_says_PASS():
    """The negative control for all of the above: don't cry wolf on a real pass."""
    line, ret = _verdict([_d("celldiag", True), _d("logstream", True)])
    assert line.startswith("PASS")
    assert "6 tests executed, 0 skipped" in line, (
        "PASS must state how much ran -- a bare PASS is what let both "
        "regressions hide")
    assert ret == 0


def test_a_real_failure_outranks_the_nothing_ran_verdict():
    """A nonzero pytest rc is a FAIL even if discovery looks incomplete --
    something ran and it broke; that is the more urgent fact."""
    line, ret = _verdict([_d("celldiag", True), _d("logstream", False)], rc=1)
    assert "FAIL" in line and "rc=1" in line
    assert ret == 1


def test_parse_junit_separates_passed_from_skipped(tmp_path):
    """The parse step itself, against a real pytest junit document.

    An all-skipped and an all-passed run are indistinguishable by exit code and
    plainly different here.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    (tmp_path / "j.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="a"/>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="b">'
        '<skipped message="no replay capture"/></testcase>'
        '<testcase classname="celltools.tests.test_celldiag_logstream_parity" name="c">'
        '<failure message="mismatch"/></testcase>'
        '</testsuite></testsuites>')
    counts = gauge.parse_junit(tmp_path / "j.xml")
    assert (counts["celldiag"].passed, counts["celldiag"].skipped) == (1, 1)
    assert counts["celldiag"].reason == "no replay capture"
    assert counts["logstream"].failed == 1
    assert not counts["celldiag"].executed, "a skip means it did not fully run"
    assert not counts["logstream"].executed


def test_a_missing_junit_report_is_not_read_as_success(tmp_path):
    """If the report never got written, the counts must be empty -- i.e. NO-OP.

    Failing open here would restore the original bug by a new route.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    counts = gauge.parse_junit(tmp_path / "absent.xml")
    assert all(not c.executed for c in counts.values())


# ── A tree that CANNOT be configured is a host fact, not an omission ──
#
# On a host without libwebsockets, `./configure` hard-fails:
#
#     checking for libwebsockets >= 3.1.0... no
#     configure: error: Package requirements (libwebsockets >= 3.1.0) were not met
#
# The drivers under test do not use libwebsockets themselves; the contract is
# gated on a Kismet SERVER dependency only because the documented build path is
# the top-level autoconf configure. Telling the operator to run `./configure`
# there is a remedy that cannot work, i.e. a skip whose stated cause is wrong.

def test_a_tree_that_cannot_be_configured_is_its_own_status(tmp_path, monkeypatch):
    """`not-configured` (an omission) vs `not-configurable` (a host fact)."""
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    monkeypatch.delenv("CELLDIAG_PARITY_BUILD", raising=False)
    _unconfigured_clone(tmp_path, monkeypatch)
    monkeypatch.setattr(parity, "missing_configure_deps",
                        lambda clone: ["libwebsockets"])

    found = parity.discover("celldiag", allow_build=True)
    assert found.status == "not-configurable", \
        f"a host missing a configure dep reported as {found.status!r}"
    assert not found.ok


def test_the_unconfigurable_remedy_names_the_package_not_configure(tmp_path,
                                                                   monkeypatch):
    """The remedy must NOT be `./configure`.

    Advising a command that hard-fails is worse than advising nothing: it reads
    as "you forgot a step" when the truth is "this machine cannot do it", and
    the operator burns a cycle discovering that."""
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    _unconfigured_clone(tmp_path, monkeypatch)
    monkeypatch.setattr(parity, "missing_configure_deps",
                        lambda clone: ["libwebsockets"])

    reason = parity.discover("celldiag").skip_reason()
    assert "libwebsockets" in reason, "the missing module is not named"
    assert "libwebsockets-dev" in reason, "no installable package named"
    assert "run `cd" not in reason and "./configure`, then" not in reason, \
        f"the unconfigurable remedy still tells the operator to ./configure: {reason}"


def test_every_role_records_whether_it_has_a_standalone_build(tmp_path,
                                                              monkeypatch):
    """The two tables must PARTITION ``ROLES``.

    A role in neither leaves role-generic code reaching for a fact it does not
    have, and filling the gap with prose written about some other role. ``_standalone_note`` degrades to an explicit
    "unrecorded" rather than a wrong sentence, and this asserts we never ship
    that."""
    assert not (set(parity._STANDALONE_ESCAPE) &
                set(parity._NO_STANDALONE_ESCAPE)), \
        "a role cannot both have and not have a standalone build"
    assert set(parity._STANDALONE_ESCAPE) | set(parity._NO_STANDALONE_ESCAPE) \
        == set(parity.ROLES), "a role's standalone status is unrecorded"
    for role in parity.ROLES:
        assert "unrecorded" not in parity._standalone_note(role, tmp_path)


def test_the_standalone_advice_names_a_makefile_that_actually_exists():
    """The escape hatch must not point at a missing file.

    The standalone build is the one documented escape from a
    `not-configurable` host, so advice naming a ``standalone.mk`` that does not
    exist is a dead end that reads exactly like advice that works. Every
    ``-C <dir> -f standalone.mk`` this module can print is checked against the
    real tree."""
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    advised = set()
    for role in parity.ROLES:
        for m in re.finditer(r"-C (\S+) -f standalone\.mk",
                             parity._standalone_note(role, clone)):
            advised.add(Path(m.group(1)))
    assert advised, "no role advises a standalone build at all"
    for d in sorted(advised):
        assert (d / "standalone.mk").is_file(), \
            f"advised `make -C {d} -f standalone.mk` but {d}/standalone.mk is absent"


@pytest.mark.parametrize("role", sorted(parity.ROLES))
def test_the_standalone_advice_never_names_another_roles_binary(role):
    """The copy-paste tell, pinned per role.

    A note that names one role's binary while advising a build in another
    role's directory and offering a third role's override variable cannot be
    acted on. A reader must be able to use this text without first checking
    which driver it was written about, so no role's note may name another
    role's binary as the thing to build."""
    note = parity._standalone_note(role, parity.tree_root() or Path("/CLONE"))
    mine = Path(parity.ROLES[role][1]).name
    for other, (_, rel, _) in parity.ROLES.items():
        binary = Path(rel).name
        if other == role or binary == mine:
            continue
        assert f"build it{binary}" not in note, note
        # The `logstream` escape is deliberately cross-referenced from the roles
        # that have none -- as a NAMED OTHER role, never as this role's remedy.
        if binary in note:
            assert f"`{other}` role" in note or f"{other}-dump" in note, \
                f"{role}'s note names {binary} without saying whose it is: {note}"


def test_the_cellat_standalone_makefile_covers_every_lws_free_binary():
    """A selftest added to Makefile.in and not to standalone.mk goes MISSING.

    ``standalone.mk`` is a hand-maintained mirror of the framework-free recipes
    in ``Makefile.in`` -- it cannot include them, because Makefile.in's first
    line is ``include ../Makefile.inc``, itself generated by configure. That
    makes drift the obvious failure mode, and drift here is silent: the
    unconfigurable host simply never runs the new check. So the mirror is
    asserted rather than trusted.

    ``make check``'s prerequisite list in Makefile.in is the source of truth for
    "framework-free selftest", since anything needing the framework could not be
    a bare ``$(CC)`` recipe there either."""
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    d = clone / "capture_cell_at"
    template = (d / "Makefile.in").read_text()
    standalone = (d / "standalone.mk").read_text()

    binvars = dict(re.findall(r"^(\w+_BIN)\s*=\s*(\S+)\s*$", template, re.M))
    check = re.search(r"^check:((?:.*\\\n)*.*)$", template, re.M).group(1)
    expected = {binvars[v] for v in re.findall(r"\$\((\w+_BIN)\)", check)}
    assert expected, "could not resolve Makefile.in's `check` prerequisites"

    covered = set(re.findall(r"^\t(test_\w+)", standalone, re.M)) | \
        set(re.split(r"\s+", re.search(r"^TESTS\s*=\s*((?:.*\\\n)*.*)$",
                                       standalone, re.M).group(1)
                     .replace("\\\n", " ").strip()))
    missing = expected - covered
    assert not missing, \
        (f"capture_cell_at/standalone.mk does not build {sorted(missing)}, "
         f"which `make check` runs -- an unconfigurable host silently skips them")


def test_the_cellat_standalone_makefile_lists_and_defines_each_selftest_once():
    """A mirror fix applied twice is also drift.

    A selftest listed twice in ``TESTS`` with its recipe defined twice makes
    make only warn ("overriding recipe"), ``check`` then runs the test twice,
    and the coverage test above stays green, so duplicates are asserted here."""
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    standalone = (clone / "capture_cell_at" / "standalone.mk").read_text()

    tests = re.split(r"\s+", re.search(r"^TESTS\s*=\s*((?:.*\\\n)*.*)$",
                                       standalone, re.M).group(1)
                     .replace("\\\n", " ").strip())
    listed_twice = sorted({t for t in tests if tests.count(t) > 1})
    assert not listed_twice, f"standalone.mk TESTS lists {listed_twice} more than once"

    targets = re.findall(r"^([\w$()]+):(?!=)", standalone, re.M)
    defined_twice = sorted({t for t in targets if targets.count(t) > 1})
    assert not defined_twice, f"standalone.mk defines {defined_twice} more than once"


def test_unconfigurable_is_benign_but_unconfigured_is_not():
    """The avoidable/unavoidable split, stated once.

    `no-tree` and `not-configurable` are facts about the machine; the operator
    can do nothing about them IN THIS TREE, so a `--check` must not read as a
    finding. `not-configured` IS one command away and must still flag."""
    import celldiag_parity_status as gauge
    assert "not-configurable" in gauge._BENIGN
    assert "not-configured" not in gauge._BENIGN


def _header_root(tmp_path, *, present: bool):
    """A synthetic ``_HEADER_ROOTS`` entry, with or without the probed header.

    The tests below must control this. ``_HEADER_ROOTS`` is three ABSOLUTE
    system paths (``/usr/include``, ...), so ``tmp_path`` does not isolate the
    header probe -- ``tmp_path`` isolates the ``clone`` argument, which that
    probe never reads. Left uncontrolled, these assertions would depend on
    whether the developer's host has ``libsensors-dev`` installed.
    """
    root = tmp_path / ("with-headers" if present else "without-headers")
    for header in parity._CONFIGURE_HEADER_DEPS:
        path = root / header
        if present:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("/* synthetic */\n")
    root.mkdir(parents=True, exist_ok=True)
    return root


def test_the_dep_probe_does_not_guess_when_pkg_config_is_absent(tmp_path,
                                                                monkeypatch):
    """No pkg-config -> we cannot tell about the PKG-CONFIG deps, so name none.

    Returning "everything is missing" would substitute one wrong cause for
    another, which is the failure this whole status family exists to avoid.

    The contract is "we do not guess about the half we cannot measure", NOT
    "we return nothing" -- the header probe is answerable without pkg-config and
    still reports (next test). The headers are forced PRESENT here so this
    assertion is about the pkg-config half alone and holds on every host."""
    monkeypatch.setattr(parity, "_HEADER_ROOTS",
                        (str(_header_root(tmp_path, present=True)),))
    monkeypatch.setattr(parity.shutil, "which", lambda name: None)
    assert parity.missing_configure_deps(tmp_path) == []


def test_a_missing_header_is_still_reported_when_pkg_config_is_absent(
        tmp_path, monkeypatch):
    """The other half of the same contract.

    ``missing_configure_deps`` runs two probes and only one goes through
    ``which``. The header probe stands alone deliberately: a missing header is
    a fact we CAN establish on a host with no pkg-config, and the gauge must
    not print a remedy that hard-fails. Suppressing it to make the sibling test's ``== []``
    true would trade a measurable cause for an invented one."""
    monkeypatch.setattr(parity, "_HEADER_ROOTS",
                        (str(_header_root(tmp_path, present=False)),))
    monkeypatch.setattr(parity.shutil, "which", lambda name: None)
    assert parity.missing_configure_deps(tmp_path) == \
        sorted(parity._CONFIGURE_HEADER_DEPS)


def test_every_named_header_dep_carries_an_installable_remedy(tmp_path,
                                                              monkeypatch):
    """A dep must never be named without a remedy.

    ``_dep_remedy`` indexes ``_CONFIGURE_HEADER_DEPS`` with ``[]`` after a
    ``.get`` miss on the pkg table, so a header added to the probe list without
    a remedy raises ``KeyError`` from inside the gauge rather than printing a
    hint. Pinned here so the failure surfaces as a test, not as a traceback on
    an operator's terminal."""
    monkeypatch.setattr(parity, "_HEADER_ROOTS",
                        (str(_header_root(tmp_path, present=False)),))
    monkeypatch.setattr(parity.shutil, "which", lambda name: None)
    for dep in parity.missing_configure_deps(tmp_path):
        assert parity._dep_remedy(dep).strip(), f"{dep} names no remedy"


def test_the_named_deps_are_not_used_by_the_drivers_under_test():
    """The finding itself, pinned so it cannot quietly stop being true.

    If capture_cell_diag ever DOES take a libwebsockets dependency, the
    argument that "the contract is gated on an irrelevant dep" changes, and this
    fails rather than the docs going quietly stale.

    This test measures the directory, not the link closure. The link closure
    is ``test_the_capture_framework_keeps_every_lws_reference_behind_its_ifdef``
    below. Kept because the narrow fact is still worth a trip-wire -- the
    drivers' own sources really do not use lws -- but it must not be read
    alone."""
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    src = clone / "capture_cell_diag"
    hits = []
    for f in list(src.glob("*.c")) + list(src.glob("*.cpp")) + list(src.glob("*.h")):
        text = f.read_text(errors="replace")
        if "libwebsockets" in text or "lws_" in text:
            hits.append(f.name)
    assert not hits, (
        f"capture_cell_diag now references libwebsockets ({hits}) -- the "
        "premise was that the drivers under test use none of the configure-time "
        "deps that gate the contract. Re-check _CONFIGURE_PKG_DEPS.")


def _lws_unguarded_lines(text: str) -> list[tuple[int, str]]:
    """Lines naming libwebsockets that sit OUTSIDE an ``#ifdef HAVE_LIBWEBSOCKETS``.

    Tracks the preprocessor stack: an ``#ifdef``/``#if`` on the macro opens a
    positive frame, ``#ifndef``/``#if !`` a negative one, ``#else`` flips it. A
    line is guarded when any enclosing frame is positive.
    """
    stack: list[int] = []
    bad = []
    for n, line in enumerate(text.splitlines(), 1):
        s = line.strip()
        m = re.match(r"#\s*(ifdef|ifndef|if|elif|else|endif)\b(.*)", s)
        if m:
            kw, rest = m.group(1), m.group(2)
            lws = "HAVE_LIBWEBSOCKETS" in rest
            if kw == "ifdef":
                stack.append(1 if lws else 0)
            elif kw == "ifndef":
                stack.append(-1 if lws else 0)
            elif kw == "if":
                stack.append((-1 if "!" in rest else 1) if lws else 0)
            elif kw == "elif" and stack:
                stack[-1] = 0
            elif kw == "else" and stack:
                stack[-1] = -stack[-1]
            elif kw == "endif" and stack:
                stack.pop()
            continue
        if ("lws_" in line or "libwebsockets.h" in line) and 1 not in stack:
            bad.append((n, s))
    return bad


def test_the_lws_scanner_flags_an_unguarded_reference():
    """Positive control for the invariant below: a gauge that never reads
    positive cannot be read as negative."""
    assert _lws_unguarded_lines(
        "#include <libwebsockets.h>\nstruct x { struct lws_context *c; };\n")
    assert _lws_unguarded_lines(
        "#ifndef HAVE_LIBWEBSOCKETS\nstruct lws_ring *r;\n#endif\n")
    assert _lws_unguarded_lines(
        "#ifdef HAVE_LIBWEBSOCKETS\n#else\nstruct lws_vhost *v;\n#endif\n")
    assert not _lws_unguarded_lines(
        "#ifdef HAVE_LIBWEBSOCKETS\n#include <libwebsockets.h>\n"
        "#ifdef SYS_LINUX\nstruct lws_context *c;\n#endif\n#endif\n")


def test_the_capture_framework_keeps_every_lws_reference_behind_its_ifdef():
    """The capture framework's libwebsockets use stays behind its ``#ifdef``.

    What matters is the LINK CLOSURE, not the driver directory:
    ``kismet_cap_cell_*`` link capture_framework. Every lws include, every
    ``struct lws_*`` member and every lws call site there is under
    ``#ifdef HAVE_LIBWEBSOCKETS``, so with the macro undefined both capture
    drivers link against libc alone (Darwin: libSystem only). The dependency is
    a configure choice, and the standalone ``baseline`` builds make it optional.

    That holds only while no lws reference sits outside the guard. One
    unguarded ``lws_`` line breaks every no-lws build, including Darwin, while
    every Linux host that has lws stays green.
    """
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    for name in ("capture_framework.h", "capture_framework.c"):
        f = clone / name
        if not f.exists():
            pytest.skip(f"this tree has no {name}")
        bad = _lws_unguarded_lines(f.read_text(errors="replace"))
        assert not bad, (
            f"{name} references libwebsockets outside #ifdef HAVE_LIBWEBSOCKETS "
            f"at {bad[:5]} -- the no-lws baseline (Linux without lws, every "
            f"Darwin parity run) can no longer compile")

    # The logstream driver must stay framework-free: it is the one leg that
    # needs no framework at all, and so the one runnable with only libc.
    dump_src = clone / "capture_cell_diag" / "diag_logstream.c"
    if dump_src.exists():
        body = dump_src.read_text(errors="replace")
        assert "capture_framework" not in body and "lws_" not in body, (
            "diag_logstream.c now pulls in the capture framework")


def test_a_standalone_build_path_exists_for_the_half_that_can_have_one():
    """A standalone build path exists for capture_cell_diag.

    Asserts the file takes NO autoconf input. ``Makefile.in`` exists in that
    directory and is NOT a standalone path -- it is rendered by the top-level
    ``config.status`` and its first line is ``include ../Makefile.inc``, itself
    generated by ``configure``. *"It already has a Makefile.in"* is exactly the
    reasoning this test exists to refuse.
    """
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    mk = clone / "capture_cell_diag" / "standalone.mk"
    assert mk.exists(), "capture_cell_diag/standalone.mk is missing"

    body = mk.read_text(errors="replace")

    # Comment lines are stripped first. The file's own header EXPLAINS why
    # Makefile.in's `include ../Makefile.inc` disqualifies it, so a naive
    # substring search over the whole text matches the explanation and reports
    # the opposite of the truth. Assert on what make will execute.
    code = "\n".join(
        line for line in body.splitlines() if not line.lstrip().startswith("#")
    )
    assert "include ../Makefile.inc" not in code, (
        "standalone.mk includes the configure-generated Makefile.inc, so it is "
        "not standalone at all"
    )
    assert "@" + "CC@" not in code, "standalone.mk carries an autoconf substitution"

    # It must build the parity driver and offer a check target, or it does not
    # reduce the "unverified here" surface.
    assert "diag_logstream_dump" in body
    assert "check:" in body

    # ...and it MUST build the helper as the Python-decode baseline.
    #
    # "Builds without ./configure" is the property this file exists for: no
    # rendered ../Makefile.inc, no generated ../config.h, no ../diagspec/ C++
    # closure. "Builds without libwebsockets" is a separate property, and also
    # holds because the framework's lws code is #ifdef'd.
    assert "$(BASELINE_BIN):" in code or "kismet_cap_cell_diag:" in code, (
        "standalone.mk no longer builds the helper. The Python-decode baseline "
        "must stay buildable on a tree that has never run ./configure -- that "
        "is the reference configuration all native-decode work is subordinate to"
    )
    assert "baseline:" in code, "standalone.mk lost its `baseline` target"

    # The baseline is the PYTHON-decode configuration: it must link no native
    # decode objects. A `.cpp` source reaching in from ../diagspec/ here would
    # make the target a second native build wearing the baseline's name, and
    # every guard downstream would still pass.
    #
    # Asserted on SOURCES, not on -I flags: include paths do not link
    # anything; compiled sources do.
    diagspec_srcs = [
        tok
        for tok in code.split()
        if tok.startswith("../diagspec/") and tok.endswith((".cpp", ".cc"))
    ]
    assert not diagspec_srcs, (
        "standalone.mk compiles native decode sources into the baseline: "
        f"{diagspec_srcs}. The baseline links ZERO native decode objects by "
        "definition -- with them it is a native build wearing the baseline's "
        "name, and every guard downstream still passes."
    )


def test_the_standalone_baseline_does_not_write_the_autoconf_output_path():
    """Two makefiles must not share one output path.

    If ``standalone.mk``'s ``BASELINE_BIN`` equals ``Makefile.in``'s
    ``MONITOR_BIN``, running the documented buildability check --

        make -C capture_cell_diag -f standalone.mk baseline

    -- inside a CONFIGURED tree silently replaces the autoconf-built helper with
    a differently-built one (different ``config.h`` resolution, different ``-I``
    order, different link line), and every consumer afterwards measures the
    wrong artifact.

    Every other guard passes on either binary: both builds exit 0, both are
    legitimately role ``baseline`` so ``check_binary_symbols.sh`` is green, and
    ``.native_mode`` reads ``baseline`` either way. The symptom surfaces as
    unrelated-looking failures in argument handling, nowhere near the build
    system. ``celltools/Makefile``'s ``replay-gate`` keeps the NATIVE=1/baseline
    pair apart for the same reason; this pins that standalone.mk keeps its
    output elsewhere too.
    """
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")

    d = clone / "capture_cell_diag"
    mk_in = d / "Makefile.in"
    mk_alone = d / "standalone.mk"
    if not (mk_in.exists() and mk_alone.exists()):
        pytest.skip("this tree has no capture_cell_diag build files")

    def _assign(text: str, var: str) -> str | None:
        """The single-line value of ``var = ...``, comments stripped."""
        for line in text.splitlines():
            if line.lstrip().startswith("#"):
                continue
            m = re.match(rf"{re.escape(var)}\s*[:?]?=\s*(.*)", line.strip())
            if m:
                return m.group(1).strip()
        return None

    monitor = _assign(mk_in.read_text(errors="replace"), "MONITOR_BIN")
    baseline = _assign(mk_alone.read_text(errors="replace"), "BASELINE_BIN")
    baseline_dir = _assign(mk_alone.read_text(errors="replace"), "BASELINE_DIR")

    assert monitor, "could not parse MONITOR_BIN out of Makefile.in"
    assert baseline, "could not parse BASELINE_BIN out of standalone.mk"
    assert baseline_dir, "could not parse BASELINE_DIR out of standalone.mk"

    assert baseline != monitor, (
        f"standalone.mk writes {baseline!r}, the SAME path Makefile.in's "
        f"MONITOR_BIN writes. In a configured tree the buildability check then "
        f"clobbers the deliverable, and no guard downstream can tell."
    )

    # ...and specifically it must land under the directory standalone.mk owns
    # outright -- anywhere else is a new shared path rather than a fixed one.
    assert baseline.startswith("$(BASELINE_DIR)/"), (
        f"BASELINE_BIN is {baseline!r}; it must live under $(BASELINE_DIR) "
        f"({baseline_dir!r}), which standalone.mk owns and .gitignore covers"
    )


def test_standalone_baseline_module_set_matches_the_autoconf_one():
    """The two module lists are a hand-maintained MIRROR, and mirrors drift.

    ``standalone.mk``'s ``BASELINE_CELLDIAG_SRCS`` and ``Makefile.in``'s
    ``MONITOR_OBJS`` name the same pure-C module set in two files. Nothing makes
    them agree, and a divergence is silent in the worst direction: the
    standalone baseline builds, links, and passes its symbol guard while missing
    a module the autoconf build has (``diag_logstream`` is the one the
    logstream parity check runs on).

    Both files already pin their own COUNT at link time. A count catches a drop;
    it does not catch a swap. This diffs the names.
    """
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")

    d = clone / "capture_cell_diag"
    mk_in = d / "Makefile.in"
    mk_alone = d / "standalone.mk"
    if not (mk_in.exists() and mk_alone.exists()):
        pytest.skip("this tree has no capture_cell_diag build files")

    def _block(text: str, var: str) -> set[str]:
        """The whitespace/backslash-continued value of `var = ...`."""
        out: list[str] = []
        collecting = False
        for line in text.splitlines():
            stripped = line.strip()
            if not collecting:
                if stripped.startswith(f"{var} ="):
                    collecting = True
                    stripped = stripped.split("=", 1)[1].strip()
                else:
                    continue
            more = stripped.endswith("\\")
            out.extend(stripped.rstrip("\\").split())
            if not more:
                break
        return {t for t in out if t.endswith((".c", ".c.o"))}

    autoconf = {n[: -len(".o")] if n.endswith(".c.o") else n
                for n in _block(mk_in.read_text(errors="replace"), "MONITOR_OBJS")}
    standalone = _block(mk_alone.read_text(errors="replace"), "BASELINE_CELLDIAG_SRCS")

    assert autoconf, "could not parse MONITOR_OBJS out of Makefile.in"
    assert standalone, "could not parse BASELINE_CELLDIAG_SRCS out of standalone.mk"
    assert autoconf == standalone, (
        "the standalone baseline and the autoconf baseline disagree on the "
        f"pure-C module set.\n"
        f"  only in Makefile.in:   {sorted(autoconf - standalone)}\n"
        f"  only in standalone.mk: {sorted(standalone - autoconf)}"
    )


def test_partial_reports_the_test_fraction_not_just_the_harness_fraction():
    """`PARTIAL` must convey its MAGNITUDE, not just the word.

    `PARTIAL -- 1/3 harnesses ran` is also what a legitimately-degraded host
    prints, so two thirds of the contract going unrun reads as routine.

    A harness count cannot convey the magnitude because harnesses are wildly
    unequal: celldiag alone is 43 of the 63 tests, so `1/3 harnesses` and
    `2/3 harnesses` can mean 16/63 or 53/63 tests. The test fraction is what
    makes a half-run legible at a glance instead of needing a manual A/B.
    """
    line, ret = _verdict([_d("celldiag", True), _d("logstream", True)],
                         celldiag={"passed": 0, "skipped": 43,
                                   "reason": "no capture directory"},
                         logstream={"passed": 4, "skipped": 0})
    assert "PARTIAL" in line
    # 4 of 47 tests ran -- the number that makes the shortfall visible.
    assert "4/47 tests" in line, line
    assert "1/2 harnesses" in line, line
    assert ret == 0


def test_a_full_run_does_not_carry_a_fraction():
    """The fraction belongs to PARTIAL only; PASS already means everything
    ran, so adding a ratio there would be noise."""
    line, ret = _verdict([_d("celldiag", True), _d("logstream", True)])
    assert "PASS" in line and "tests ran" not in line
    assert ret == 0


# --------------------------------------------------------------------------
# Skip CLASSIFICATION -- a skip count is the wrong shape for the question "is
# this expected?", and a single reason line misreports a heterogeneous skip
# set. A run with 7 skips (6 for reason A, 1 for the two-build replay gate)
# must not render as `7 skipped (<reason A>)`, and the gauge must be able to
# say which skips are expected-by-configuration and which are new.
# --------------------------------------------------------------------------

#: The two skip reasons a correctly-configured parity run is EXPECTED to
#: produce, verbatim enough to be greppable in the harness sources.
_MEASURED_EXPECTED = [
    "kismet_cap_cell_diag is a Python-decode baseline build (no native decode "
    "legs linked), so nativedecode=shadow is refused by design. Rebuild with "
    "'make NATIVE=1' in capture_cell_diag to run this test. Full path: /x",
    "CELLDIAG_BASELINE_BIN unset — build both configurations with "
    "`make -C celltools replay-gate`",
]


def test_parse_junit_records_EVERY_distinct_skip_reason_not_just_the_first():
    """The skip under-report, at its source.

    ``Counts.reason`` keeps only the FIRST reason pytest recorded, so a harness
    that skipped for two different causes would render as
    ``N skipped (<cause 1>)`` -- true about one test and false about the set.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    c = gauge.Counts(passed=3, skipped=3,
                     reasons={"reason A": 2, "reason B": 1})
    assert c.reason == "reason A", "the first reason stays available"
    assert c.reasons == {"reason A": 2, "reason B": 1}
    assert sum(c.reasons.values()) == c.skipped, (
        "the census must account for every skip, or it is the same "
        "under-report in a new place")


def test_parse_junit_populates_the_census_from_a_real_junit_document(tmp_path):
    import celldiag_parity_status as gauge  # noqa: E402
    (tmp_path / "j.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="a">'
        '<skipped message="cause one"/></testcase>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="b">'
        '<skipped message="cause one"/></testcase>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="c">'
        '<skipped message="cause two"/></testcase>'
        '</testsuite></testsuites>')
    counts = gauge.parse_junit(tmp_path / "j.xml")
    assert counts["celldiag"].reasons == {"cause one": 2, "cause two": 1}


@pytest.mark.parametrize("reason", _MEASURED_EXPECTED)
def test_the_two_measured_skips_classify_as_EXPECTED(reason):
    """Both real parity-run skips are configuration facts, not findings."""
    import celldiag_parity_status as gauge  # noqa: E402
    expected, unexpected = gauge.classify_skips({reason: 1})
    assert unexpected == {}, f"misclassified as a finding: {reason}"
    assert [n for _, n, _ in expected] == [1]


def test_an_unrecognised_skip_reason_is_UNEXPECTED():
    """The negative control. Without it the classifier could return
    ``expected`` unconditionally and every test above would still pass."""
    import celldiag_parity_status as gauge  # noqa: E402
    expected, unexpected = gauge.classify_skips({"no replay capture": 12})
    assert expected == []
    assert unexpected == {"no replay capture": 12}


def test_every_expected_skip_names_why_AND_a_remedy():
    """A classification with no remedy just relabels the silence."""
    import celldiag_parity_status as gauge  # noqa: E402
    for e in gauge.EXPECTED_SKIPS:
        assert e.match and e.why and e.remedy, e


def test_every_expected_skip_pattern_still_matches_a_LIVE_harness_skip():
    """The guard that makes shrinking this table fail loudly.

    A reworded skip message degrades safely -- it stops matching and shows up
    as UNEXPECTED, which is exactly the alarm we want. The DANGEROUS direction
    is the other one: a pattern that no longer corresponds to any skip in any
    harness silently shrinks the classifier to a no-op, and a table of dead
    patterns classifies nothing while looking authoritative.

    So each pattern must be findable in a harness source. The count is pinned
    too, because a table that loses an entry passes a per-entry loop trivially.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    assert len(gauge.EXPECTED_SKIPS) == 5, (
        "pinned: adding or removing an expected skip is a decision, not a "
        "refactor -- update this number and say why in the changelog")
    # The capture corpus lives outside git, so its reachability is a HOST fact
    # (like `no-tree`), and classing it UNEXPECTED would flag a regression on
    # every host without the corpus. The baseline-build skip mirrors the
    # shadow-refusal entry. `not-configurable` is benign in discovery, so its
    # skips must be expected in the run phase too; its text is composed by
    # `Discovery.skip_reason()` in celldiag_parity.py, never a literal in a
    # harness, so that module is read too.
    sources = "\n".join(
        (Path(gauge.CELLTOOLS) / rel).read_text()
        for rel in [*gauge.HARNESS.values(), "celldiag_parity.py"])
    for e in gauge.EXPECTED_SKIPS:
        assert e.match in sources, (
            f"expected-skip pattern is DEAD -- no harness emits it any more, "
            f"so it classifies nothing: {e.match!r}")


def test_partial_splits_the_skips_into_expected_and_unexpected():
    """The verdict answers "is this a regression?"
    instead of handing the operator a number to compare against prose."""
    import celldiag_parity_status as gauge  # noqa: E402
    line, ret = _verdict(
        [_d("celldiag", True), _d("logstream", True)],
        celldiag={"passed": 37, "skipped": 7,
                  "reasons": {_MEASURED_EXPECTED[0]: 6,
                              _MEASURED_EXPECTED[1]: 1}},
        logstream={"passed": 4, "skipped": 0})
    assert "PARTIAL" in line
    assert "7 skipped (7 expected-by-configuration, 0 unexpected)" in line, line
    assert ret == 0


def test_an_unexpected_skip_is_NAMED_in_the_verdict_not_just_counted():
    """A count of unexpected skips with no reason attached is the same
    under-report one level up."""
    import celldiag_parity_status as gauge  # noqa: E402
    line, ret = _verdict(
        [_d("celldiag", True), _d("logstream", True)],
        celldiag={"passed": 37, "skipped": 8,
                  "reasons": {_MEASURED_EXPECTED[0]: 6,
                              _MEASURED_EXPECTED[1]: 1,
                              "no replay capture": 1}},
        logstream={"passed": 4, "skipped": 0})
    assert "1 unexpected" in line, line
    assert "no replay capture" in line, (
        "an unexpected skip must carry its reason -- naming only the count "
        "leaves the operator unable to tell what is new")
    assert ret == 0


def test_a_verdict_built_from_the_legacy_reason_field_still_classifies():
    """Back-compat: a ``Counts`` carrying only ``reason`` (no census) must not
    silently classify as zero skips of any kind."""
    import celldiag_parity_status as gauge  # noqa: E402
    line, _ = _verdict([_d("celldiag", True), _d("logstream", True)],
                       celldiag={"passed": 0, "skipped": 43,
                                 "reason": "no capture directory"},
                       logstream={"passed": 4, "skipped": 0})
    assert "43 unexpected" in line, line
    assert "no capture directory" in line


# ── STALE-DRIVER: a red that is not a parity break ──────────────────────────
# Both fixtures are verbatim harness output from a run where every failure was
# driver staleness and none was an assertion. Synthesised strings would prove
# only that the classifier matches what was written for it.
_MEASURED_STALE = [
    "KP_CELLAT_BIN is STALE: /src/kismet/capture_cell_at/"
    "kismet_cap_cell_at is older than its sources (capture_cell_at.c, "
    "capture_framework.c, version.h). [dependency set: derived — 23 sources "
    "from 4 objects + 1 linked archive(s) in Makefile's rule for "
    "kismet_cap_cell_at] Rebuild: (cd /src/kismet && make "
    "capture_cell_at/kismet_cap_cell_at)",
    "REBUILD NEEDED: make -C /src/kismet/capture_cell_diag "
    "kismet_cap_cell_diag — kismet_cap_cell_diag is older than its sources "
    "(capture_cell_diag.c, diag_ifclass.c, version.h). Usually means something "
    "restamped the sources without rebuilding. This harness only means "
    "anything against a current binary — a stale one silently tests code "
    "nobody shipped. [dependency set: derived — 60 sources from 35 objects + 1 "
    "linked archive(s) in Makefile's rule for kismet_cap_cell_diag] Full path: "
    "/src/kismet/capture_cell_diag/kismet_cap_cell_diag",
]


@pytest.mark.parametrize("message", _MEASURED_STALE)
def test_both_measured_staleness_spellings_classify_as_stale(message):
    """There are TWO staleness spellings, and both must classify.

    The cellat harness says ``KP_CELLAT_BIN is STALE``; the celldiag harness
    leads with ``REBUILD NEEDED:`` instead (pytest's short summary shows the
    first line, so the fix goes first). A one-pattern classifier would leave
    most stale runs reported as FAIL.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    stale, other = gauge.classify_failures({message: 1})
    assert other == {}, f"misclassified as a real failure: {message[:60]}"
    assert [n for _, n, _ in stale] == [1]


def test_a_real_assertion_failure_is_NOT_classified_as_staleness():
    """The negative control. Without it the classifier could return ``stale``
    unconditionally and every test above would still pass."""
    import celldiag_parity_status as gauge  # noqa: E402
    stale, other = gauge.classify_failures({"assert 3 == 4": 2})
    assert stale == []
    assert other == {"assert 3 == 4": 2}


def test_an_all_staleness_run_is_STALE_DRIVER_not_FAIL():
    """``FAIL`` is documented as 'a real breakage,
    investigate' -- for this cause that is misleading in the expensive
    direction, and the remedy is one command the failure text already prints.
    """
    line, ret = _verdict(
        [_d("celldiag", True), _d("cellat", True)], rc=1,
        celldiag={"passed": 0, "failed": 57,
                  "failures": {_MEASURED_STALE[1]: 57}},
        cellat={"passed": 0, "failed": 18,
                "failures": {_MEASURED_STALE[0]: 18}})
    assert "STALE-DRIVER" in line, line
    assert "FAIL" not in line, line
    assert "75" in line, "the operator needs the magnitude, not just the word"


def test_STALE_DRIVER_still_exits_NON_ZERO():
    """Renaming the verdict must not turn it into a pass.

    Nothing was measured: the guard REFUSED to run against a binary that does
    not correspond to its sources. That is the 'nothing ran, so nothing
    complained' shape, and it exits 1 for the same reason NO-OP does.
    """
    _, ret = _verdict(
        [_d("celldiag", True)], rc=1,
        celldiag={"passed": 0, "failed": 57,
                  "failures": {_MEASURED_STALE[1]: 57}})
    assert ret == 1


def test_ONE_real_failure_among_many_stale_ones_keeps_the_verdict_FAIL():
    """The dangerous direction, and the reason this is decided per run.

    An operator who meets a red with a one-command remedy twice learns the
    shortcut. If a genuine parity break could hide among 74 staleness failures
    and be relabelled STALE-DRIVER, the classifier would be strictly worse than
    no classifier.
    """
    line, ret = _verdict(
        [_d("celldiag", True), _d("cellat", True)], rc=1,
        celldiag={"passed": 0, "failed": 57,
                  "failures": {_MEASURED_STALE[1]: 56,
                               "assert obs['pci'] == 431": 1}},
        cellat={"passed": 0, "failed": 18,
                "failures": {_MEASURED_STALE[0]: 18}})
    assert "FAIL" in line, line
    assert "STALE-DRIVER" not in line, line
    assert ret == 1


def test_a_MIXED_run_names_the_real_failure_and_discounts_the_stale_noise():
    """Staying FAIL is necessary but not sufficient -- the operator still has
    to find the one real failure among 75. The verdict says which is which."""
    line, _ = _verdict(
        [_d("celldiag", True), _d("cellat", True)], rc=1,
        celldiag={"passed": 0, "failed": 57,
                  "failures": {_MEASURED_STALE[1]: 56,
                               "assert obs['pci'] == 431": 1}},
        cellat={"passed": 0, "failed": 18,
                "failures": {_MEASURED_STALE[0]: 18}})
    assert "assert obs['pci'] == 431" in line, line
    assert "74" in line, "the stale count must be stated so it can be ignored"


def test_a_failing_run_with_NO_recorded_messages_stays_FAIL():
    """Absence of evidence is not evidence of staleness.

    A junit report that is missing, truncated, or produced by a collection
    error yields rc!=0 with an empty failure census. Classifying that as
    STALE-DRIVER would put the friendliest possible label on the least
    understood possible run.
    """
    line, ret = _verdict([_d("celldiag", True)], rc=1,
                         celldiag={"passed": 0, "failed": 57})
    assert "FAIL" in line, line
    assert "STALE-DRIVER" not in line, line
    assert ret == 1


def test_parse_junit_records_failure_messages_not_just_a_count(tmp_path):
    """``parse_junit`` must keep failure messages, not only a counter.

    Without them, by the time ``verdict`` sees a red, why it was red has
    already been thrown away.

    This drives ``parse_junit`` against a real junit document on purpose: a
    hand-built ``Counts`` asserted against itself says nothing about the
    function that has to fill it.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    (tmp_path / "j.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="a">'
        f'<failure message="{_MEASURED_STALE[1][:40]}"/></testcase>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="b">'
        f'<failure message="{_MEASURED_STALE[1][:40]}"/></testcase>'
        '<testcase classname="celltools.tests.test_cellat_ipc" name="c">'
        '<failure message="assert 3 == 4"/></testcase>'
        '</testsuite></testsuites>')
    counts = gauge.parse_junit(tmp_path / "j.xml")
    assert counts["celldiag"].failed == 2
    assert counts["celldiag"].failures == {_MEASURED_STALE[1][:40]: 2}
    assert counts["cellat"].failures == {"assert 3 == 4": 1}


def test_parse_junit_reads_an_ERROR_element_the_same_way_as_a_FAILURE(tmp_path):
    """``parse_junit`` has always counted ``<error>`` beside ``<failure>``.

    A collection or fixture error carries its text the same way, and dropping
    it would leave the census empty for a whole class of red -- which the
    verdict then reads as "no evidence", i.e. FAIL. Safe, but it would hide
    the one case where the message is most informative.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    (tmp_path / "j.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite>'
        '<testcase classname="celltools.tests.test_cellat_ipc" name="a">'
        '<error message="fixture &apos;modem&apos; not found"/></testcase>'
        '</testsuite></testsuites>')
    counts = gauge.parse_junit(tmp_path / "j.xml")
    assert counts["cellat"].failed == 1
    assert counts["cellat"].failures == {"fixture 'modem' not found": 1}


def test_a_failure_element_with_no_message_attribute_falls_back_to_its_BODY(tmp_path):
    """pytest puts a long ``pytest.fail()`` text in the element body.

    Both staleness spellings are long, so this is not a hypothetical: if the
    body were ignored, the exact failures this feature exists to classify
    would arrive with an empty census and be reported as plain FAIL.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    (tmp_path / "j.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite>'
        '<testcase classname="celltools.tests.test_celldiag_replay_ab" name="a">'
        f'<failure>{_MEASURED_STALE[1][:40]}</failure></testcase>'
        '</testsuite></testsuites>')
    counts = gauge.parse_junit(tmp_path / "j.xml")
    assert counts["celldiag"].failures == {_MEASURED_STALE[1][:40]: 1}


def test_the_mixed_verdict_names_the_real_failure_TEXT_not_only_a_count():
    """Pins the naming itself, not the sentence introducing it.

    Asserting on the label ("The real ones:") alone cannot tell the label from
    the payload, so the failure text and its count are asserted directly.
    """
    line, _ = _verdict(
        [_d("celldiag", True)], rc=1,
        celldiag={"passed": 0, "failed": 3,
                  "failures": {_MEASURED_STALE[1]: 2,
                               "assert obs['earfcn'] == 5110": 1}})
    assert "assert obs['earfcn'] == 5110" in line, line
    assert "[×1]" in line, (
        "each real failure must carry its own count -- with two distinct real "
        "failures a bare list cannot say which one happened 40 times")


def test_every_stale_driver_pattern_still_matches_a_LIVE_harness_source():
    """The dead-pattern guard, mirroring the expected-skip one above.

    A reworded staleness message degrades safely: it stops matching and the
    verdict falls back to FAIL, which is the conservative direction. The
    DANGEROUS direction is a pattern matching nothing -- the classifier
    silently becomes a no-op while looking authoritative.

    The patterns must be contiguous IN SOURCE, which is not the same as
    contiguous at runtime. All three emitters print 'is older than its
    sources', but the logstream harness splits that phrase across an f-string
    join, so it cannot serve as a pattern.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    assert len(gauge.STALE_DRIVER_PATTERNS) == 2, (
        "pinned: adding or removing a staleness pattern is a decision -- a "
        "table that loses an entry passes a per-entry loop trivially")
    sources = "\n".join(
        (Path(gauge.CELLTOOLS) / rel).read_text()
        for rel in gauge.HARNESS.values())
    for s in gauge.STALE_DRIVER_PATTERNS:
        assert s.match in sources, (
            f"staleness pattern is DEAD -- no harness emits it any more, so "
            f"it classifies nothing: {s.match!r}")


def test_every_stale_driver_pattern_names_why_and_a_remedy():
    """A classification with no remedy just relabels the red."""
    import celldiag_parity_status as gauge  # noqa: E402
    for s in gauge.STALE_DRIVER_PATTERNS:
        assert s.match and s.why and s.remedy, s


def test_the_stale_patterns_do_not_match_the_ordinary_pytest_vocabulary():
    """Guard against a pattern loose enough to swallow real failures.

    ``is STALE: `` and ``REBUILD NEEDED: `` are specific strings, but this
    pins that intent: if either is ever loosened to something like ``stale``
    or ``rebuild``, an ordinary failure mentioning those words in passing
    would be relabelled and the mixed-run guard above would not catch it,
    because there would be nothing left in ``other``.
    """
    import celldiag_parity_status as gauge  # noqa: E402
    innocent = {
        "assert 'the cache is stale' in caplog.text": 1,
        "AssertionError: rebuild needed after the mask change": 1,
        "E   assert 0 == 1": 1,
    }
    stale, other = gauge.classify_failures(innocent)
    assert stale == [], f"a real failure was swallowed: {stale}"
    assert other == innocent


# ── STALE-DRIVER must offer ONE convergent rebuild, not per-driver ───────────
#
# The drivers share libkismetdatasource.a. Following a per-driver remedy rebuilds
# that archive, restamping it newer than the OTHER (previously current) drivers,
# so the next gauge run reports STALE-DRIVER again for a different driver and
# reads as though the first remedy failed. The verdict must name a single
# command that rebuilds EVERY discovered driver, so one pass converges.
def test_convergent_rebuild_chains_every_discovered_driver():
    cmd = parity.convergent_rebuild_for(
        [_d("celldiag", True), _d("logstream", True), _d("cellat", True)])
    assert cmd is not None
    assert cmd.count("make -C ") == 3        # all three drivers, one line
    assert " && " in cmd
    assert "kismet_cap_cell_diag" in cmd
    assert "diag_logstream_dump" in cmd
    assert "kismet_cap_cell_at" in cmd


def test_convergent_rebuild_skips_unbuilt_discoveries():
    # a not-configured driver (path None) contributes nothing
    cmd = parity.convergent_rebuild_for(
        [_d("celldiag", True), _d("cellat", True), _d("logstream", False)])
    assert cmd is not None
    assert cmd.count("make -C ") == 2
    assert "diag_logstream_dump" not in cmd


def test_convergent_rebuild_is_None_for_a_single_built_driver():
    # one driver -> no shared-archive cascade, the per-driver make line already converges
    assert parity.convergent_rebuild_for([_d("celldiag", True)]) is None
    assert parity.convergent_rebuild_for(
        [_d("celldiag", True), _d("cellat", False)]) is None


def test_STALE_DRIVER_verdict_names_the_ONE_convergent_command():
    line, ret = _verdict(
        [_d("celldiag", True), _d("cellat", True)], rc=1,
        celldiag={"passed": 0, "failed": 57,
                  "failures": {_MEASURED_STALE[1]: 57}},
        cellat={"passed": 0, "failed": 18,
                "failures": {_MEASURED_STALE[0]: 18}})
    assert "STALE-DRIVER" in line
    assert " && " in line, "must offer a single chained rebuild"
    assert "re-stales the others" in line
    # both drivers named in the convergent command
    assert "kismet_cap_cell_diag" in line and "kismet_cap_cell_at" in line


# ── The one-pass chain on an UNCONFIGURED tree ──────────────────────────────
# A stale built binary does not imply a configured tree: the baseline builds
# live in build-baseline/ with no Makefile anywhere. A bare
# `make -C <dir> <target>` there falls through to make's built-in rules, prints
# "Nothing to be done", exits 0 and rebuilds nothing.

# Real prerequisites, so link_dependencies() derives the closure from this
# makefile (a rule with none falls back to a glob and carries no makefile).
_STANDALONE_MK = (
    "baseline:\n\t@echo REBUILT-baseline\n"
    "build-baseline/kismet_cap_cell_diag build-baseline/kismet_cap_cell_at: "
    "drv.c\n"
    "diag_logstream_dump: dls.c\n\t@echo REBUILT-logstream\n"
    ".PHONY: baseline diag_logstream_dump\n")


def _baseline_built_clone(tmp_path):
    """An unconfigured tree after `--build`: every driver built, no Makefile."""
    clone = tmp_path / "tree"
    for role in ("celldiag", "cellat"):
        subdir, _t, out = parity._STANDALONE_ESCAPE[role]
        (clone / subdir).mkdir(parents=True, exist_ok=True)
        (clone / subdir / "standalone.mk").write_text(_STANDALONE_MK)
        (clone / subdir / "drv.c").write_text("")
        (clone / subdir / "dls.c").write_text("")
        _exe(clone / subdir / out)
    logstream = _exe(clone / "capture_cell_diag" / "diag_logstream_dump")
    return [
        parity.Discovery("celldiag", "discovered", clone / "capture_cell_diag"
                         / "build-baseline" / "kismet_cap_cell_diag", ""),
        parity.Discovery("cellat", "discovered", clone / "capture_cell_at"
                         / "build-baseline" / "kismet_cap_cell_at", ""),
        parity.Discovery("logstream", "discovered", logstream, ""),
    ]


def test_the_convergent_chain_names_standalone_mk_on_an_unconfigured_tree(
        tmp_path):
    cmd = parity.convergent_rebuild_for(_baseline_built_clone(tmp_path))
    assert cmd is not None
    links = cmd.split(" && ")
    assert len(links) == 3, links
    for link in links:
        assert "-f standalone.mk" in link, link
        assert "build-baseline" not in link, (
            f"`make -C build-baseline` names no makefile: {link}")


def test_the_convergent_chain_agrees_with_each_per_driver_remedy(tmp_path):
    """One spelling for both remedies, so they cannot drift apart again."""
    found = _baseline_built_clone(tmp_path)
    cmd = parity.convergent_rebuild_for(found)
    for d in found:
        per_driver = parity.staleness(d.role, d.path).rebuild_cmd()
        assert per_driver in cmd.split(" && "), (d.role, per_driver, cmd)


@pytest.mark.skipif(__import__("shutil").which("make") is None,
                    reason="no make on this host")
def test_every_link_of_the_convergent_chain_actually_runs_a_rule(tmp_path):
    """The behavioural half: make itself must find a rule for every link.

    A link that resolves to no rule prints `Nothing to be done` and exits 0,
    which the string tests above cannot detect.
    """
    import subprocess
    cmd = parity.convergent_rebuild_for(_baseline_built_clone(tmp_path))
    for link in cmd.split(" && "):
        out = subprocess.run(link, shell=True, capture_output=True, text=True)
        assert out.returncode == 0, (link, out.stderr)
        assert "REBUILT-" in out.stdout, (link, out.stdout, out.stderr)


# ── The capture drivers' no-configure `baseline` builds ─────────────────────
# Both capture drivers build on Linux and Darwin via standalone.mk `baseline`,
# into build-baseline/ (never the autoconf output path). Discovery, the
# `--build` path, and the staleness guard each have to know where that is.


def _exe(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\n")
    path.chmod(0o755)
    return path


def _clear_role_env(monkeypatch):
    for env_var, _, _ in parity.ROLES.values():
        monkeypatch.delenv(env_var, raising=False)
    monkeypatch.delenv("CELLDIAG_PARITY_BUILD", raising=False)


@pytest.mark.parametrize("role", ["celldiag", "cellat"])
def test_a_standalone_baseline_is_discovered_on_an_unconfigured_tree(
        role, tmp_path, monkeypatch):
    """Discovery must look beyond the autoconf output path, or a `baseline`
    built by hand is invisible and the role still skips."""
    _clear_role_env(monkeypatch)
    clone = _unconfigured_clone(tmp_path, monkeypatch)
    subdir, _target, out = parity._STANDALONE_ESCAPE[role]
    built = _exe(clone / subdir / out)

    found = parity.discover(role)
    assert found.status == "discovered", found
    assert found.path == built
    assert "standalone.mk" in found.detail


def test_the_autoconf_binary_wins_over_the_standalone_baseline(tmp_path,
                                                               monkeypatch):
    """On a configured tree the autoconf binary is what Linux users get; a side
    build must not silently become the thing measured."""
    _clear_role_env(monkeypatch)
    clone = _unconfigured_clone(tmp_path, monkeypatch)
    primary = _exe(clone / parity.ROLES["celldiag"][1])
    _exe(clone / "capture_cell_diag" / "build-baseline" / "kismet_cap_cell_diag")
    assert parity.discover("celldiag").path == primary


def test_build_on_an_unconfigured_tree_takes_the_standalone_escape(tmp_path,
                                                                   monkeypatch):
    """On an unconfigured tree `--build` builds `-f standalone.mk baseline`
    for the capture roles -- but only where standalone.mk exists, so the
    guarantee "never invoke make where it cannot work" still holds for a tree
    without one (tested above)."""
    _clear_role_env(monkeypatch)
    clone = _unconfigured_clone(tmp_path, monkeypatch)
    (clone / "capture_cell_diag" / "standalone.mk").write_text("baseline:\n")
    calls = []

    def fake_build(clone_, target, subdir="capture_cell_diag", makefile=None):
        calls.append((target, subdir, makefile))
        _exe(clone_ / subdir / "build-baseline" / "kismet_cap_cell_diag")
        return True, ""

    monkeypatch.setattr(parity, "_build", fake_build)
    found = parity.discover("celldiag", allow_build=True)
    assert calls == [("baseline", "capture_cell_diag", "standalone.mk")]
    assert found.status == "built", found
    assert found.path.parent.name == "build-baseline"


def test_a_build_baseline_binary_takes_its_closure_from_the_parent_standalone_mk(
        tmp_path):
    """The narrow-to-empty direction. A build-baseline/ binary's closure must
    not be derived from build-baseline/ itself: there is no makefile there, so
    the glob fallback finds only the generated config.h and version.c, and a
    source edit would leave the binary reading "current"."""
    src = tmp_path / "capture_cell_diag"
    bdir = src / "build-baseline"
    bdir.mkdir(parents=True)
    (tmp_path / "fw.c").write_text("")
    (tmp_path / "fw.h").write_text("")
    for name in ("a.c", "a.h", "b.inc"):
        (src / name).write_text("")
    (bdir / "config.h").write_text("")
    (src / "standalone.mk").write_text(
        "BASELINE_DIR = build-baseline\n"
        "BASELINE_BIN = $(BASELINE_DIR)/kismet_cap_cell_diag\n"
        "SRCS = a.c\n"
        "$(BASELINE_BIN): guard $(BASELINE_DIR)/config.h $(SRCS) ../fw.c ../fw.h\n"
        "\tcc -o $@ $(SRCS)\n")
    binary = _exe(bdir / "kismet_cap_cell_diag")

    deps = parity.link_dependencies(binary)
    assert deps.mode == "derived", deps.note
    names = {p.name for p in deps.sources}
    assert {"a.c", "fw.c", "fw.h", "config.h"} <= names, names
    assert {"a.h", "b.inc"} <= names, \
        "no .d files in a one-shot build: the directory's headers must be added"
    assert deps.makefile == src / "standalone.mk"

    st = parity.Staleness("celldiag", binary, (), deps)
    assert st.rebuild_cmd() == f"make -C {src} -f standalone.mk baseline"


def test_the_cellat_baseline_mirrors_monitor_objs():
    """The cellat `baseline` compiles a hand-kept copy of Makefile.in's
    MONITOR_OBJS. A module added there and not here can still link (its caller
    may sit behind a runtime branch) while silently dropping a capability."""
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    d = clone / "capture_cell_at"
    tmpl = parity._logical_lines((d / "Makefile.in").read_text())
    alone = parity._logical_lines((d / "standalone.mk").read_text())
    objs = parity._parse_vars(tmpl)["MONITOR_OBJS"].split()
    avars = parity._parse_vars(alone)
    srcs = parity._expand(avars["BASELINE_CELLAT_SRCS"], avars).split()

    assert {o[:-len(".o")] for o in objs} == {Path(s).name for s in srcs}, \
        "capture_cell_at/standalone.mk BASELINE_CELLAT_SRCS != MONITOR_OBJS"
    assert int(avars["BASELINE_SRCS_COUNT"]) == len(srcs)


def _run_config_rule(tmp_path, **mk_vars):
    """Render capture_cell_diag's baseline config.h into tmp_path via make."""
    import shutil
    import subprocess
    clone = parity.tree_root()
    if clone is None:
        pytest.skip("KP_ROOT does not point at a source tree")
    if shutil.which("make") is None:
        pytest.skip("no make on this host")
    if (clone / "config.h").exists():
        pytest.skip("configured tree: the rule COPIES ../config.h, by design")
    out = tmp_path / "bdir"
    args = [f"BASELINE_DIR={out}", *(f"{k}={v}" for k, v in mk_vars.items())]
    run = subprocess.run(
        ["make", "-C", str(clone / "capture_cell_diag"), "-f", "standalone.mk",
         *args, "baseline-platform-guard", f"{out}/config.h"],
        capture_output=True, text=True, check=False)
    cfg = out / "config.h"
    return run, (cfg.read_text() if cfg.exists() else "")


def test_the_baseline_config_names_darwin_and_can_omit_lws(tmp_path):
    """The generated config must not hardcode `#define SYS_LINUX 1` on every
    host."""
    run, cfg = _run_config_rule(tmp_path, BASELINE_TARGET_OS="Darwin", LWS=0)
    assert run.returncode == 0, run.stderr
    assert "#define SYS_DARWIN 1" in cfg
    assert "#define SYS_LINUX" not in cfg
    assert "#define HAVE_LIBWEBSOCKETS" not in cfg
    assert "#define STATUS_MAX" in cfg


def test_the_baseline_config_keeps_linux_and_lws_when_asked(tmp_path):
    """The Linux + lws configuration the old generator hardcoded is still
    what a Linux host with libwebsockets gets."""
    run, cfg = _run_config_rule(tmp_path, BASELINE_TARGET_OS="Linux", LWS=1)
    assert run.returncode == 0, run.stderr
    assert "#define SYS_LINUX 1" in cfg
    assert "#define SYS_DARWIN" not in cfg
    assert "#define HAVE_LIBWEBSOCKETS 1" in cfg


def test_the_baseline_refuses_an_unmapped_os(tmp_path):
    run, _ = _run_config_rule(tmp_path, BASELINE_TARGET_OS="Plan9", LWS=0)
    assert run.returncode != 0
    assert "no platform mapping for 'Plan9'" in run.stderr
