# standalone.mk -- build the cellat pieces that do not need ./configure
#
#   make -f standalone.mk          # cellat_serial_probe + every runnable selftest
#   make -f standalone.mk check    # ... and run the selftests
#   make -f standalone.mk clean
#
# WHY THIS FILE EXISTS
# --------------------
# Like the sibling capture_cell_diag/standalone.mk, this lets a host that cannot
# `./configure` this tree still build the AT probe and every cellat selftest
# with nothing but a C compiler. `celldiag_parity.py`'s `not-configurable`
# advice points at this file for the cellat role:
#
#     make -C <clone>/capture_cell_at -f standalone.mk
#
# `baseline` -- kismet_cap_cell_at with no autoconf input
# --------------------
#   make -f standalone.mk baseline     # -> build-baseline/kismet_cap_cell_at
#
# The driver links the capture framework, which builds without libwebsockets:
# every lws include and member in the framework is under
# `#ifdef HAVE_LIBWEBSOCKETS`. The details are in capture_cell_diag/standalone.mk;
# the shared config both drivers' baselines use is
# capture_cell_diag/baseline_platform.mk (Linux and Darwin, lws optional).
#
# So the test_cellat_ipc.py tests the gauge's `cellat` role runs are
# reachable on any host with a C compiler, including a Mac.

# These rules are a hand-maintained mirror of the `$(CC) $(CFLAGS)
# $(CPPFLAGS)` recipes in Makefile.in, which cannot be reused: its first line is
# `include ../Makefile.inc`, itself generated by configure. "It already has a
# Makefile.in" is not the same as "it can build alone". Pinned by
# test_the_cellat_standalone_makefile_covers_every_lws_free_binary in
# celltools/tests/test_celldiag_parity_discovery.py, so a selftest added to
# Makefile.in and not to this file fails a test instead of going quietly
# missing here.

CC      ?= cc
CFLAGS  ?= -Wall -g -O2

DIAGDIR = ../capture_cell_diag

# The standalone AT probe -- no Kismet link, so it needs no framework.
PROBE_BIN = cellat_serial_probe

# Every selftest in this directory that needs no capture framework. Same set
# `make check` runs from the generated Makefile, minus nothing: all eight are
# framework-free.
TESTS = \
	test_at_serial \
	test_at_serial_portability \
	test_cellat_options \
	test_cellat_portscan \
	test_cellat_qeng \
	test_cellat_qscan \
	test_cellat_cpsi \
	test_cellat_std3gpp \
	test_diag_wwanport \
	test_diag_probeclose \
	test_diag_modemident \
	test_diag_portadmit \
	test_diag_identvouch \
	test_atlog \
	test_clockanchor \
	test_cellat_tacfix \
	test_cellat_stats \
	test_cellat_optset \
	test_cellat_qmifeed \
	test_cellat_lock

all: $(PROBE_BIN) $(TESTS)

# ===========================================================================
# baseline -- kismet_cap_cell_at, with no autoconf input
# ===========================================================================
# Into $(BASELINE_DIR), not ./kismet_cap_cell_at: that is the generated
# Makefile's output path, and a second writer to it would clobber the configured
# build's binary (capture_cell_diag/standalone.mk explains the hazard).
BASELINE_DIR = build-baseline
BASELINE_BIN = $(BASELINE_DIR)/kismet_cap_cell_at

# The same translation units Makefile.in's MONITOR_OBJS names, count pinned
# for the same reason as celldiag's: a shorter list can still link (a lost
# module's callers may be behind a runtime branch) while silently dropping a
# capability. Pinned against Makefile.in by the parity-discovery test.
BASELINE_CELLAT_SRCS = \
	capture_cell_at.c \
	cellat_options.c \
	cellat_stats.c \
	cellat_optset.c \
	cellat_lock.c \
	cellat_portscan.c \
	atlog.c \
	clockanchor.c \
	cellat_qmifeed.c \
	$(DIAGDIR)/diag_wwanport.c \
	$(DIAGDIR)/diag_probeclose.c \
	$(DIAGDIR)/diag_modemident.c \
	$(DIAGDIR)/diag_portadmit.c \
	$(DIAGDIR)/diag_identvouch.c
BASELINE_SRCS_COUNT = 14

# The shared modules' headers, as prerequisites for the same reason as the
# framework's below: the staleness guard reads this rule, and there are no .d
# files in a standalone build. This directory's own *.h / *.inc are covered by
# the guard directly.
BASELINE_SHARED_HDRS = \
	$(DIAGDIR)/diag_wwanport.h \
	$(DIAGDIR)/diag_probeclose.h \
	$(DIAGDIR)/diag_modemident.h \
	$(DIAGDIR)/diag_portadmit.h \
	$(DIAGDIR)/diag_identvouch.h

# The capture framework -- what libkismetdatasource.a is, unpacked -- compiled
# from source so the target needs no prior top-level build. Its headers are
# listed too, as prerequisites: the parity gauge's staleness guard
# (celltools/celldiag_parity.py, link_dependencies) derives a build-baseline/
# binary's closure from this rule, and a closure without the framework reads
# "current" after a framework edit. Mirrored in the sibling capture directory's
# standalone.mk; both sit one level below the tree root, so the paths agree.
BASELINE_KISMET_SRCS = \
	../capture_framework.c \
	../simple_ringbuf_c.c \
	../mpack/mpack.c
BASELINE_KISMET_HDRS = \
	../capture_framework.h \
	../simple_ringbuf_c.h \
	../mpack/mpack.h \
	../kis_external_packet.h \
	../kis_endian.h \
	../remote_announcement.h \
	../version.h


# capture_cell_at.c spells it `#include "../config.h"`, which resolves against
# this directory's parent before any -I -- so on an unconfigured tree it would
# find nothing. -I$(BASELINE_DIR)/shim makes the -I search land on
# $(BASELINE_DIR)/shim/../config.h, i.e. ours. On a configured tree the parent's
# ../config.h wins first, and it is the same file baseline_platform.mk copied.
# The source's spelling is left alone: the autoconf build passes -I. only.
BASELINE_CFLAGS = -I$(BASELINE_DIR)/shim -I$(BASELINE_DIR) -I.. -I$(DIAGDIR) \
	$(BASELINE_LWS_CFLAGS) $(CFLAGS)

baseline: $(BASELINE_BIN)

# After `baseline:` -- the fragment defines rules, and `all` must stay the
# default goal of this file.
include $(DIAGDIR)/baseline_platform.mk

$(BASELINE_BIN): baseline-platform-guard \
		$(BASELINE_DIR)/config.h $(BASELINE_DIR)/version.c \
		$(BASELINE_CELLAT_SRCS) $(BASELINE_SHARED_HDRS) \
		$(BASELINE_KISMET_SRCS) $(BASELINE_KISMET_HDRS)
	@[ "$(words $(BASELINE_CELLAT_SRCS))" = "$(BASELINE_SRCS_COUNT)" ] || { \
	    echo "*** ERROR: BASELINE_CELLAT_SRCS has $(words $(BASELINE_CELLAT_SRCS)) sources, expected $(BASELINE_SRCS_COUNT) ***" >&2; \
	    echo "A module was added to or LOST from MONITOR_OBJS; mirror it here." >&2; \
	    exit 1; }
	@mkdir -p $(BASELINE_DIR)/shim
	$(CC) $(BASELINE_CFLAGS) -pthread -o $@ \
	    $(BASELINE_CELLAT_SRCS) \
	    $(BASELINE_KISMET_SRCS) $(BASELINE_DIR)/version.c \
	    -lpthread -lm $(BASELINE_CONFIG_LIBS)
	@echo "PASS: baseline $(BASELINE_BIN) built with no autoconf input"
	@echo "      (a CHECK artifact -- the tree's ./kismet_cap_cell_at is untouched)"

# Every at_serial.inc includer links the shared probe module: serial_open()'s
# open is the bounded diag_probe_open(), which runs on a worker thread.
$(PROBE_BIN): cellat_serial_probe.c at_serial.inc $(DIAGDIR)/diag_probeclose.c $(DIAGDIR)/diag_probeclose.h
	$(CC) $(CFLAGS) -pthread -o $@ cellat_serial_probe.c $(DIAGDIR)/diag_probeclose.c

test_at_serial: test_at_serial.c at_serial.inc $(DIAGDIR)/diag_probeclose.c $(DIAGDIR)/diag_probeclose.h
	$(CC) $(CFLAGS) -pthread -o $@ test_at_serial.c $(DIAGDIR)/diag_probeclose.c

# Compiles at_serial.inc with B460800/B921600 undefined, as on macOS, so a
# Linux host catches a macOS build failure of this file's `check` target.
test_at_serial_portability: test_at_serial_portability.c at_serial.inc $(DIAGDIR)/diag_probeclose.c $(DIAGDIR)/diag_probeclose.h
	$(CC) $(CFLAGS) -pthread -o $@ test_at_serial_portability.c \
	    $(DIAGDIR)/diag_probeclose.c

test_cellat_options: test_cellat_options.c cellat_options.c cellat_options.h
	$(CC) $(CFLAGS) -o $@ test_cellat_options.c cellat_options.c

# atlog JSONL tee core: path templating, JSON escaping, record format.
# libc-only, no Kismet/serial -- mirrors capture_cell_diag/test_diag_rawlog.
test_atlog: test_atlog.c atlog.c atlog.h
	$(CC) $(CFLAGS) -o $@ test_atlog.c atlog.c

# Clock-anchor core: AT+CCLK? extraction + ClockAnchor record format.
# Links clockanchor.c + atlog.c (shared JSON escaping), libc-only -- mirrors
# capture_cell_diag's rawlog selftest factoring.
test_clockanchor: test_clockanchor.c clockanchor.c clockanchor.h atlog.c atlog.h
	$(CC) $(CFLAGS) -o $@ test_clockanchor.c clockanchor.c atlog.c

# The cellat_stats control line: the omit-not-zero rule, the
# disabled shape and the profile vocabulary. libc-only.
test_cellat_stats: test_cellat_stats.c cellat_stats.c cellat_stats.h \
		cellat_options.c cellat_options.h atlog.c atlog.h
	$(CC) $(CFLAGS) -o $@ test_cellat_stats.c cellat_stats.c cellat_options.c atlog.c

# Band/RAT lock logic. libc-only.
test_cellat_lock: test_cellat_lock.c cellat_lock.c cellat_lock.h
	$(CC) $(CFLAGS) -o $@ test_cellat_lock.c cellat_lock.c

# Runtime settings via set_channel. libc-only.
test_cellat_optset: test_cellat_optset.c cellat_optset.c cellat_optset.h \
		cellat_options.c cellat_options.h
	$(CC) $(CFLAGS) -o $@ test_cellat_optset.c cellat_optset.c cellat_options.c

# The qmifeed= child. libc-only.
test_cellat_qmifeed: test_cellat_qmifeed.c cellat_qmifeed.c cellat_qmifeed.h $(DIAGDIR)/diag_privdrop.h
	$(CC) $(CFLAGS) -o $@ test_cellat_qmifeed.c cellat_qmifeed.c

# CSURVC TAC=0 substitution + the "tac":<n>:0 regression guard.
test_cellat_tacfix: test_cellat_tacfix.c cellat_tacfix.inc
	$(CC) $(CFLAGS) -o $@ test_cellat_tacfix.c

test_cellat_qeng: test_cellat_qeng.c cellat_qeng.inc
	$(CC) $(CFLAGS) -o $@ test_cellat_qeng.c

# Standard 3GPP decode cores (generic serving cell + AT+COPS=? PLMN scan); the
# std parsers reuse the qeng helpers, so both .inc files are prerequisites --
# the same pair Makefile.in names.
test_cellat_std3gpp: test_cellat_std3gpp.c cellat_std3gpp.inc cellat_qeng.inc
	$(CC) $(CFLAGS) -o $@ test_cellat_std3gpp.c

test_cellat_cpsi: test_cellat_cpsi.c cellat_cpsi.inc cellat_qeng.inc
	$(CC) $(CFLAGS) -o $@ test_cellat_cpsi.c

# AT+QSCAN=3,1 decode core: parse_qscan reuses the qeng helpers.
test_cellat_qscan: test_cellat_qscan.c cellat_qscan.inc cellat_qeng.inc
	$(CC) $(CFLAGS) -o $@ test_cellat_qscan.c

# The shared classifier lives in capture_cell_diag/ deliberately: it is
# the one predicate that knows both non-USB node-naming conventions, and two
# copies would let cellat and celldiag drift into claiming one node.
test_diag_wwanport: $(DIAGDIR)/diag_wwanport.c $(DIAGDIR)/diag_wwanport.h
	$(CC) $(CFLAGS) -DDIAG_WWANPORT_SELFTEST -o $@ $(DIAGDIR)/diag_wwanport.c

test_diag_probeclose: $(DIAGDIR)/diag_probeclose.c $(DIAGDIR)/diag_probeclose.h
	$(CC) $(CFLAGS) -pthread -DDIAG_PROBECLOSE_SELFTEST -o $@ $(DIAGDIR)/diag_probeclose.c

test_diag_modemident: $(DIAGDIR)/test_diag_modemident.c $(DIAGDIR)/diag_modemident.c $(DIAGDIR)/diag_modemident.h
	$(CC) $(CFLAGS) -I$(DIAGDIR) -o $@ $(DIAGDIR)/test_diag_modemident.c $(DIAGDIR)/diag_modemident.c

test_cellat_portscan: cellat_portscan.c cellat_portscan.h \
	    $(DIAGDIR)/diag_wwanport.c $(DIAGDIR)/diag_wwanport.h \
	    $(DIAGDIR)/diag_portadmit.c $(DIAGDIR)/diag_portadmit.h
	$(CC) $(CFLAGS) -DCELLAT_PORTSCAN_SELFTEST -o $@ cellat_portscan.c \
	    $(DIAGDIR)/diag_wwanport.c $(DIAGDIR)/diag_portadmit.c

# The identity vouch: cellat writes it for the AT port it holds.
test_diag_identvouch: $(DIAGDIR)/test_diag_identvouch.c $(DIAGDIR)/diag_identvouch.c $(DIAGDIR)/diag_identvouch.h $(DIAGDIR)/diag_modemident.c $(DIAGDIR)/diag_modemident.h
	$(CC) $(CFLAGS) -I$(DIAGDIR) -o $@ $(DIAGDIR)/test_diag_identvouch.c $(DIAGDIR)/diag_identvouch.c $(DIAGDIR)/diag_modemident.c

# The shared scan admission that decides cellat's suspected sources.
test_diag_portadmit: $(DIAGDIR)/diag_portadmit.c $(DIAGDIR)/diag_portadmit.h
	$(CC) $(CFLAGS) -DDIAG_PORTADMIT_SELFTEST -o $@ $(DIAGDIR)/diag_portadmit.c

check: $(TESTS)
	@for t in $(TESTS); do echo "--- $$t"; ./$$t || exit 1; done
	@echo "PASS: standalone cellat selftests"

# ===========================================================================
# functional -- cellat's own self-test: qmifeed=auto delivers a cell
# ===========================================================================
# The claim: the baseline binary this tree builds, pointed at a modem, finds the
# QMI feed that ships beside it (qmifeed/) and relays at least one src:qmi cell,
# with no venv, no PYTHONPATH and no file from outside the tree.
#
# The modem and the qmicli are the tree's own fakes (celltools/tests/
# fake_at_modem.py on a pty; a shell stub answering canned EM9291 output), and
# whatever runs this target supplies no input, as with capture_cell_diag's. A
# harness that brought its own fakes would prove the harness plus the tree, not
# the tree.
#
# System python3: `qmifeed=auto` execs `python3` off $PATH, so that is the
# interpreter an ordinary run uses; the checker runs under the same one.
# Linux or macOS: it needs a pty and the baseline binary, nothing else.
PYTHON ?= python3

functional: $(BASELINE_BIN)
	@echo "--- qmifeed=auto through $(BASELINE_BIN), a fake AT modem and a fake qmicli"
	env -u PYTHONPATH -u VIRTUAL_ENV \
	    $(PYTHON) fixtures/check_qmifeed_functional.py $(BASELINE_BIN)
	@echo "PASS: functional -- cellat ran the tree's own QMI feed with no external input"

clean:
	rm -f $(PROBE_BIN) $(TESTS)
	rm -rf $(BASELINE_DIR)

.PHONY: all baseline check clean functional
