#!/bin/sh

# Generate version.c.
#
# This script runs on every build (Makefile.in: `version.c: FORCE`).  A
# `version.c:` rule with no prerequisites never regenerates the file once it
# exists, so the string would freeze at whatever commit was checked out the
# first time the tree was built.  That is not cosmetic: the version is stamped
# into WiGLE CSV uploads and .kismet logs, so a frozen string misattributes
# captured data to a commit that did not produce it.
#
# Running every build makes the conditional write load-bearing.  make keys on
# mtime, so unconditionally rewriting identical bytes would relink the ~540MB
# server on every no-op build.  version.c is therefore written only when its
# content actually changed -- the same write-if-changed idiom that
# capture_cell_diag/Makefile's .native_mode stamp uses, for the same reason.

# The fork's identity.  This tree is the AT+DIAG cellular-PHY fork, not stock
# Kismet, and data it captures must be traceable to that.
#
# Carried as its own symbol rather than folded into VERSION_MAJOR/MINOR/TINY
# on purpose: the WiGLE CSV header's `release=` field is built from those three
# and WiGLE parses it, so they stay numeric and date-shaped exactly as upstream
# emits them.  Only `appRelease=` gains the fork name.
VERSION_POC_NAME="KismetCell"

rev=$(git rev-parse --short HEAD 2>/dev/null || echo "non-git-release")

# A build from a modified working tree is not the commit it claims to be, and
# during active development that is the normal case -- so say so.  Tracked
# modifications only: version.c itself is untracked and gitignored, and counting
# untracked files would leave every build permanently dirty.
if git rev-parse --git-dir >/dev/null 2>&1; then
    if ! git diff --quiet HEAD -- 2>/dev/null; then
        rev="${rev}-dirty"
    fi
fi

if test $# -ge 1; then
    BUILD_TIME=$1
else
    BUILD_TIME=$(date -u)
fi

if test $# -ge 2; then
    VERSION_MAJOR=$(echo "$2" | cut -f 1 -d\-)
    VERSION_MINOR=$(echo "$2" | cut -f 2 -d\-)
    VERSION_TINY=$(echo "$2" | cut -f 3 -d\-)
else
    VERSION_MAJOR=$(date '+%Y')
    VERSION_MINOR=$(date '+%m')
    VERSION_TINY="0"
fi

tmpfile="version.c.tmp.$$"

cat << EOF > "$tmpfile"
/*
    This file is part of Kismet

    Kismet is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Kismet is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Kismet; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    This file is automatically generated during compilation.
*/

const char *VERSION_POC_NAME = "$VERSION_POC_NAME";

const char *VERSION_MAJOR = "$VERSION_MAJOR";
const char *VERSION_MINOR = "$VERSION_MINOR";
const char *VERSION_TINY = "$VERSION_TINY";

const char *VERSION_GIT_COMMIT = "$rev";
const char *VERSION_BUILD_TIME = "$BUILD_TIME";
EOF

# Compare ignoring VERSION_BUILD_TIME.  That line changes on every invocation,
# so including it would make the file differ every time and defeat the point.
# Excluding it is also the semantically correct answer: when nothing else
# changed we do not relink, so the binary on disk really was built at the time
# the existing file records.  Keeping the old timestamp describes the artifact;
# overwriting it would describe a build that never happened.  (This also keeps
# SOURCE_DATE_EPOCH reproducible builds honest.)
if [ -f version.c ] && \
   grep -v '^const char \*VERSION_BUILD_TIME' "$tmpfile" > "$tmpfile.new" && \
   grep -v '^const char \*VERSION_BUILD_TIME' version.c > "$tmpfile.old" && \
   cmp -s "$tmpfile.new" "$tmpfile.old"; then
    rm -f "$tmpfile" "$tmpfile.new" "$tmpfile.old"
else
    rm -f "$tmpfile.new" "$tmpfile.old"
    mv -f "$tmpfile" version.c
fi
